Data sources:

https://pokeapi.co/docs/v2#pokemon

https://www.kaggle.com/datasets/mrdew25/pokemon-database

https://github.com/pokemondb/database/blob/master/data/moves.yaml
    
https://github.com/nbely/Bulbapedia-Pokedex-Web-Scraper/tree/master/Data
    
https://github.com/lgreski/pokemonData/blob/master/Pokemon.csv
    
https://www.kaggle.com/datasets/guavocado/pokemon-stats-1025-pokemons?resource=download
    
https://github.com/zonination/pokemon-chart/blob/master/chart.csv

# Import Libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import itertools
import warnings
import yaml
import streamlit as st
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# Read Tables

## Pokemon Database

In [2]:
pokemon_database = pd.read_csv('C:/Users/adria/Downloads/pokemon_data/pokemon_database.csv')

In [629]:
pokemon_database

,Pokemon Id,Pokedex Number,Pokemon Name,Classification,Alternate Form Name,Original Pokemon ID,Legendary Type,Pokemon Height,Pokemon Weight,Primary Type,Secondary Type,Primary Ability,Primary Ability Description,Secondary Ability,Secondary Ability Description,Hidden Ability,Hidden Ability Description,Special Event Ability,Special Event Ability Description,Male Ratio,Female Ratio,Base Happiness,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Health EV,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth,Experience Growth Total,Primary Egg Group,Secondary Egg Group,Egg Cycle Count,Pre-Evolution Pokemon Id,Evolution Details,generation
0,1,1,Bulbasaur,Seed Pokémon,NaN,NaN,NaN,0.7,6.9,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's HP is low.,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunlight.,NaN,NaN,87.5,12.5,50,Red,45,49,49,65,65,45,318,0,0,0,1,0,0,1,45,Medium Slow,1059860,Monster,Grass,20,NaN,NaN,1.0
1,2,2,Ivysaur,Seed Pokémon,NaN,NaN,NaN,1.0,13.0,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's HP is low.,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunlight.,NaN,NaN,87.5,12.5,50,Red,60,62,63,80,80,60,405,0,0,0,1,1,0,2,45,Medium Slow,1059860,Monster,Grass,20,1.0,Level 16,1.0
2,3,3,Venusaur,Seed Pokémon,NaN,NaN,NaN,2.0,100.0,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's HP is low.,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunlight.,NaN,NaN,87.5,12.5,50,Red,80,82,83,100,100,80,525,0,0,0,2,1,0,3,45,Medium Slow,1059860,Monster,Grass,20,2.0,Level 32,1.0
3,4,3,Venusaur,Seed Pokémon,Mega,3.0,NaN,2.4,155.5,Grass,Poison,Thick Fat,"The Pokémon is protected by a layer of thick fat, which halves the damage taken from Fire- and Ice-type moves.",NaN,NaN,NaN,NaN,NaN,NaN,87.5,12.5,70,X,80,100,123,122,120,80,625,0,0,0,2,1,0,3,45,Medium Slow,1059860,Monster,Grass,20,NaN,NaN,6.0
4,1526,3,Venusaur,Seed Pokémon,Gigantamax,3.0,NaN,24.0,0.0,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's HP is low.,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunlight.,NaN,NaN,87.5,12.5,50,Sword,80,82,83,100,100,80,525,0,0,0,2,1,0,3,45,Medium Slow,1059860,Monster,Grass,20,NaN,NaN,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1377,1873,1023,Iron Crown,Paradox Pokémon,NaN,NaN,NaN,1.6,156.0,Steel,Psychic,Quark Drive,Boosts the Pokémon's most proficient stat on Electric Terrain or if the Pokémon is holding Booster Energy.,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,Scarlet,90,72,100,122,108,98,590,0,0,0,3,0,0,3,10,Slow,1250000,No Eggs Discovered,NaN,50,NaN,NaN,9.0
1378,1882,1024,Terapagos,Tera Pokémon,Stellar,1769.0,Legendary,1.7,77.0,Normal,NaN,Teraform Zero,"When Terapagos changes into its Stellar Form, it uses its hidden powers to eliminate all effects of weather and terrain, reducing them to zero.",NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,Violet,160,105,110,130,110,85,700,3,0,0,0,0,0,3,255,Slow,1250000,No Eggs Discovered,NaN,0,NaN,NaN,9.0
1379,1769,1024,Terapagos,Tera Pokémon,NaN,NaN,Legendary,0.2,6.5,Normal,NaN,Tera Shift,"When the Pokémon enters a battle, it absorbs the energy around itself and transforms into its Terastal Form.",NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,Violet,90,65,85,65,85,60,450,0,0,1,0,0,0,1,255,Slow,1250000,No Eggs Discovered,NaN,0,NaN,NaN,9.0
1380,1770,1024,Terapagos,Tera Pokémon,Terastal,1769.0,Legendary,0.3,16.0,Normal,NaN,Tera Shell,The Pokémon's shell contains the powers of each type. All damage-dealing moves that hit the Pokémon when its HP is full will not be very effective.,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,Scarlet,95,95,110,105,110,85,600,0,0,2,0,2,0,4,255,Slow,1250000,No Eggs Discovered,NaN,0,NaN,NaN,9.0
1381,1884,1025,Pecharunt,Subjugation Pokémon,NaN,NaN,Mythical,0.3,0.3,Poison,Ghost,Poison Puppeteer,Pokémon poisoned by Pecharunt's moves will also become confused.,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0,Scarlet,88,88,160,88,88,88,600,0,0,3,0,0,0,3,3,Slow,1250000,No Eggs Discovered,NaN,0,NaN,NaN,9.0

## Abilities

In [96]:
bulbapedia_abilities = pd.read_csv('C:/Users/adria/Downloads/pokemon_data/bulbapedia_data.csv')

In [101]:
bulbapedia_abilities.head()

,Dex No.,Name,Base Species,Base Forme,Forme,Classification,Generation,Primary Type,Secondary Type,Ability 1,Ability 2,Hidden Ability,Gender,Male Gender Ratio,Female Gender Ratio,Catch Rate,Egg Group 1,Egg Group 2,Hatch Time Cycles,Height (In),Height (M),Weight (Lbs),Weight (Kg),Mega Stone 1,Mega Stone 2,EXP Yield (Gen I),EXP Yield (Gen II),EXP Yield (Gen III),EXP Yield (Gen IV),EXP Yield (Gen V+),Leveling Rate,EV Yield (HP),EV Yield (Attack),EV Yield (Defense),EV Yield (Sp.Atk),EV Yield (Sp.Def),EV Yield (Speed),Shape Img URL,Footprint Img Url,Base Friendship,Base HP,Base Attack,Base Defense,Base Special Attack,Base Special Defense,Base Speed,Base Stat Total,Color
0,1,Bulbasaur,NaN,NaN,NaN,Seed,1,Grass,Poison,Overgrow,NaN,Chlorophyll,NaN,0.875,0.125,45,Monster,Grass,20,28,0.7,15.2,6.9,NaN,NaN,64.0,64.0,64.0,64.0,64,Medium Slow,0,0,0,1,0,0,https://archives.bulbagarden.net/media/upload/c/cc/Body08.png,https://archives.bulbagarden.net/media/upload/d/d1/F0001.png,70,45|45|45|45|45|45|45|45|45,49|49|49|49|49|49|49|49|49,49|49|49|49|49|49|49|49|49,65|65|65|65|65|65|65|65|65,65|65|65|65|65|65|65|65|65,45|45|45|45|45|45|45|45|45,318|318|318|318|318|318|318|318|318,Green
1,2,Ivysaur,NaN,NaN,NaN,Seed,1,Grass,Poison,Overgrow,NaN,Chlorophyll,NaN,0.875,0.125,45,Monster,Grass,20,39,1.0,28.7,13.0,NaN,NaN,141.0,141.0,141.0,141.0,142,Medium Slow,0,0,0,1,1,0,https://archives.bulbagarden.net/media/upload/c/cc/Body08.png,https://archives.bulbagarden.net/media/upload/4/4a/F0002.png,70,60|60|60|60|60|60|60|60|60,62|62|62|62|62|62|62|62|62,63|63|63|63|63|63|63|63|63,80|80|80|80|80|80|80|80|80,80|80|80|80|80|80|80|80|80,60|60|60|60|60|60|60|60|60,405|405|405|405|405|405|405|405|405,Green
2,3,Venusaur,NaN,NaN,NaN,Seed,1,Grass,Poison,Overgrow,NaN,Chlorophyll,NaN,0.875,0.125,45,Monster,Grass,20,79,2.0,220.5,100.0,Venusaurite,NaN,208.0,208.0,208.0,208.0,236,Medium Slow,0,0,0,2,1,0,https://archives.bulbagarden.net/media/upload/c/cc/Body08.png,https://archives.bulbagarden.net/media/upload/8/8e/F0003.png,70,80|80|80|80|80|80|80|80|80,82|82|82|82|82|82|82|82|82,83|83|83|83|83|83|83|83|83,100|100|100|100|100|100|100|100|100,100|100|100|100|100|100|100|100|100,80|80|80|80|80|80|80|80|80,525|525|525|525|525|525|525|525|525,Green
3,3,Venusaur-Mega,Venusaur,NaN,Mega,Seed,6,Grass,Poison,Thick Fat,NaN,NaN,NaN,0.875,0.125,45,Monster,Grass,20,94,2.4,342.8,155.5,Venusaurite,NaN,208.0,208.0,208.0,208.0,236,Medium Slow,0,0,0,2,1,0,https://archives.bulbagarden.net/media/upload/c/cc/Body08.png,https://archives.bulbagarden.net/media/upload/8/8e/F0003.png,70,|||||80|80|80|80,|||||100|100|100|100,|||||123|123|123|123,|||||122|122|122|122,|||||120|120|120|120,|||||80|80|80|80,|||||625|625|625|625,Green
4,3,Venusaur-Gmax,Venusaur,NaN,Gmax,Seed,8,Grass,Poison,Overgrow,NaN,Chlorophyll,NaN,0.875,0.125,45,Monster,Grass,20,945,24.0,220.5,100.0,Venusaurite,NaN,208.0,208.0,208.0,208.0,236,Medium Slow,0,0,0,2,1,0,https://archives.bulbagarden.net/media/upload/c/cc/Body08.png,https://archives.bulbagarden.net/media/upload/8/8e/F0003.png,70,|||||||80|80,|||||||82|82,|||||||83|83,|||||||100|100,|||||||100|100,|||||||80|80,|||||||525|525,Green

## Stats

In [92]:
pokemon_stats = pd.read_csv('C:/Users/adria/Downloads/pokemon_data/pokemon_full_pokedex.csv')

In [93]:
pokemon_stats.head()

,ID,Name,Form,Type1,Type2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,,Grass,Poison,318,45,49,49,65,65,45,1
1,2,Ivysaur,,Grass,Poison,405,60,62,63,80,80,60,1
2,3,Venusaur,,Grass,Poison,525,80,82,83,100,100,80,1
3,4,Charmander,,Fire,,309,39,52,43,60,50,65,1
4,5,Charmeleon,,Fire,,405,58,64,58,80,65,80,1

## Info

In [85]:
pokemon_info = pd.read_csv('C:/Users/adria/Downloads/pokemon_data/pokemon_info.csv')

In [91]:
pokemon_info.head()

,dexnum,name,generation,type1,type2,species,height,weight,ability1,ability2,hidden_ability,hp,attack,defense,sp_atk,sp_def,speed,total,ev_yield,catch_rate,base_friendship,base_exp,growth_rate,egg_group1,egg_group2,percent_male,percent_female,egg_cycles,special_group
0,1,Bulbasaur,1,Grass,Poison,Seed Pokémon,0.7,6.9,Overgrow,Chlorophyll,NaN,45,49,49,65,65,45,318,1 Sp. Atk,45,50,64,Medium Slow,Grass,Monster,87.5,12.5,20,Ordinary
1,2,Ivysaur,1,Grass,Poison,Seed Pokémon,1.0,13.0,Overgrow,Chlorophyll,NaN,60,62,63,80,80,60,405,"1 Sp. Atk, 1 Sp. Def",45,50,142,Medium Slow,Grass,Monster,87.5,12.5,20,Ordinary
2,3,Venusaur,1,Grass,Poison,Seed Pokémon,2.0,100.0,Overgrow,Chlorophyll,NaN,80,82,83,100,100,80,525,"2 Sp. Atk, 1 Sp. Def",45,50,236,Medium Slow,Grass,Monster,87.5,12.5,20,Ordinary
3,4,Charmander,1,Fire,NaN,Lizard Pokémon,0.6,8.5,Blaze,Solar Power,NaN,39,52,43,60,50,65,309,1 Speed,45,50,62,Medium Slow,Dragon,Monster,87.5,12.5,20,Ordinary
4,5,Charmeleon,1,Fire,NaN,Flame Pokémon,1.1,19.0,Blaze,Solar Power,NaN,58,64,58,80,65,80,405,"1 Sp. Atk, 1 Speed",45,50,142,Medium Slow,Dragon,Monster,87.5,12.5,20,Ordinary

## Types Chart

In [24]:
types_chart = pd.read_csv('C:/Users/adria/Downloads/pokemon_data/chart.csv')

In [25]:
types_chart

,Attacking,Normal,Fire,Water,Electric,Grass,Ice,Fighting,Poison,Ground,Flying,Psychic,Bug,Rock,Ghost,Dragon,Dark,Steel,Fairy
0,Normal,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.5,0.0,1.0,1.0,0.5,1.0
1,Fire,1,0.5,0.5,1.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,0.5,1.0,0.5,1.0,2.0,1.0
2,Water,1,2.0,0.5,1.0,0.5,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,0.5,1.0,1.0,1.0
3,Electric,1,1.0,2.0,0.5,0.5,1.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0
4,Grass,1,0.5,2.0,1.0,0.5,1.0,1.0,0.5,2.0,0.5,1.0,0.5,2.0,1.0,0.5,1.0,0.5,1.0
5,Ice,1,0.5,0.5,1.0,2.0,0.5,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,0.5,1.0
6,Fighting,2,1.0,1.0,1.0,1.0,2.0,1.0,0.5,1.0,0.5,0.5,0.5,2.0,0.0,1.0,2.0,2.0,0.5
7,Poison,1,1.0,1.0,1.0,2.0,1.0,1.0,0.5,0.5,1.0,1.0,1.0,0.5,0.5,1.0,1.0,0.0,2.0
8,Ground,1,2.0,1.0,2.0,0.5,1.0,1.0,2.0,1.0,0.0,1.0,0.5,2.0,1.0,1.0,1.0,2.0,1.0
9,Flying,1,1.0,1.0,0.5,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,0.5,1.0,1.0,1.0,0.5,1.0
10,Psychic,1,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,0.5,1.0,1.0,1.0,1.0,0.0,0.5,1.0
11,Bug,1,0.5,1.0,1.0,2.0,1.0,0.5,0.5,1.0,0.5,2.0,1.0,1.0,0.5,1.0,2.0,0.5,0.5
12,Rock,1,2.0,1.0,1.0,1.0,2.0,0.5,1.0,0.5,2.0,1.0,2.0,1.0,1.0,1.0,1.0,0.5,1.0
13,Ghost,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,0.5,1.0,1.0
14,Dragon,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,0.5,0.0
15,Dark,1,1.0,1.0,1.0,1.0,1.0,0.5,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,0.5,1.0,0.5
16,Steel,1,0.5,0.5,0.5,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,0.5,2.0
17,Fairy,1,0.5,1.0,1.0,1.0,1.0,2.0,0.5,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,0.5,1.0

In [27]:
df_melted = types_chart.melt(id_vars=["Attacking"], var_name="Defense Type", value_name="Multiplier")

df_melted["Key"] = range(1, len(df_melted) + 1)

types_chart_final = df_melted[["Key", "Attacking", "Defense Type", "Multiplier"]]

types_chart_final

     Key Attacking Defense Type  Multiplier
0      1    Normal       Normal         1.0
1      2      Fire       Normal         1.0
2      3     Water       Normal         1.0
3      4  Electric       Normal         1.0
4      5     Grass       Normal         1.0
..   ...       ...          ...         ...
319  320     Ghost        Fairy         1.0
320  321    Dragon        Fairy         0.0
321  322      Dark        Fairy         0.5
322  323     Steel        Fairy         2.0
323  324     Fairy        Fairy         1.0

[324 rows x 4 columns]

## Moves

In [581]:
with open('C:/Users/adria/Downloads/pokemon_data/moves.yaml', 'r') as file:
    dados_yaml = yaml.safe_load(file)

dados_moves = []

for move, info in dados_yaml.items():
    move_data = {
        'name': info.get('name', ''),
        'type': info.get('type', ''),
        'category': info.get('category', ''),
        'power': info.get('power', ''),
        'accuracy': info.get('accuracy', ''),
        'pp': info.get('pp', ''),
        'priority': info.get('priority', '')
    }
    dados_moves.append(move_data)

df_moves = pd.DataFrame(dados_moves)

In [582]:
df_moves

,name,type,category,power,accuracy,pp,priority
0,"10,000,000 Volt Thunderbolt",electric,special,195.0,NaN,1.0,0
1,Absorb,grass,special,20.0,100.0,25.0,0
2,Accelerock,rock,physical,40.0,100.0,20.0,1
3,Acid,poison,special,40.0,100.0,30.0,0
4,Acid Armor,poison,status,NaN,NaN,20.0,0
...,...,...,...,...,...,...,...
929,Yawn,normal,status,NaN,NaN,10.0,0
930,Zap Cannon,electric,special,120.0,50.0,5.0,0
931,Zen Headbutt,psychic,physical,80.0,90.0,15.0,0
932,Zing Zap,electric,physical,80.0,100.0,10.0,0
933,Zippy Zap,electric,physical,50.0,100.0,15.0,2

## API Moves Learned

In [607]:
def pegar_move(poke):
    
    dados_moves = []
    
    for i in poke['moves']:
        
        move_name = i['move']['name']
        
        for version_group_detail in i['version_group_details']:
            
            dados_moves.append({
            'move_name': move_name,
            'level_learned_at': version_group_detail['level_learned_at'],
            'move_learn_method': version_group_detail['move_learn_method']['name'],
            'origin': version_group_detail['version_group']['name']
        })
            
        
        df_moves = pd.DataFrame(dados_moves)
        
    return df_moves
        

def moves_pokemon(poke):
    
    pokemon_lower = poke.lower()
    
    api = f'https://pokeapi.co/api/v2/pokemon/{pokemon_lower}'
    
    res = requests.get(api)
    
    if res.status_code == 200:
        poke = res.json()
        
        return pegar_move(poke)
    
    else:
        print("Error fetching Pokémon data.")
        return None

In [614]:
df_moves_pokemon = moves_pokemon('Charmander')

In [613]:
df_moves_pokemon

,move_name,level_learned_at,move_learn_method,origin
0,mega-punch,0,machine,red-blue
1,mega-punch,0,machine,yellow
2,mega-punch,0,tutor,emerald
3,mega-punch,0,tutor,firered-leafgreen
4,mega-punch,0,machine,sword-shield
...,...,...,...,...
1156,power-up-punch,0,machine,x-y
1157,power-up-punch,0,machine,omega-ruby-alpha-sapphire
1158,breaking-swipe,0,machine,scarlet-violet
1159,tera-blast,0,machine,scarlet-violet
1160,temper-flare,0,machine,scarlet-violet

# Data Manipulation

New column and removing " " in the Pokemon Database table

In [4]:
pokemon_database = pokemon_database.applymap(lambda x: x.replace('"', '') if isinstance(x, str) else x)

In [175]:
pokemon_database.head()

,Pokemon Id,Pokedex Number,Pokemon Name,Classification,Alternate Form Name,Original Pokemon ID,Legendary Type,Pokemon Height,Pokemon Weight,Primary Type,Secondary Type,Primary Ability,Primary Ability Description,Secondary Ability,Secondary Ability Description,Hidden Ability,Hidden Ability Description,Special Event Ability,Special Event Ability Description,Male Ratio,Female Ratio,Base Happiness,Game(s) of Origin,Health Stat,Attack Stat,Defense Stat,Special Attack Stat,Special Defense Stat,Speed Stat,Base Stat Total,Health EV,Attack EV,Defense EV,Special Attack EV,Special Defense EV,Speed EV,EV Yield Total,Catch Rate,Experience Growth,Experience Growth Total,Primary Egg Group,Secondary Egg Group,Egg Cycle Count,Pre-Evolution Pokemon Id,Evolution Details,generation
0,1,1,Bulbasaur,Seed Pokémon,NaN,NaN,NaN,0.7,6.9,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunli...,NaN,NaN,87.5,12.5,50,Red,45,49,49,65,65,45,318,0,0,0,1,0,0,1,45,Medium Slow,1059860,Monster,Grass,20,NaN,NaN,1.0
1,2,2,Ivysaur,Seed Pokémon,NaN,NaN,NaN,1.0,13.0,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunli...,NaN,NaN,87.5,12.5,50,Red,60,62,63,80,80,60,405,0,0,0,1,1,0,2,45,Medium Slow,1059860,Monster,Grass,20,1.0,Level 16,1.0
2,3,3,Venusaur,Seed Pokémon,NaN,NaN,NaN,2.0,100.0,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunli...,NaN,NaN,87.5,12.5,50,Red,80,82,83,100,100,80,525,0,0,0,2,1,0,3,45,Medium Slow,1059860,Monster,Grass,20,2.0,Level 32,1.0
3,4,3,Venusaur,Seed Pokémon,Mega,3.0,NaN,2.4,155.5,Grass,Poison,Thick Fat,The Pokémon is protected by a layer of thick f...,NaN,NaN,NaN,NaN,NaN,NaN,87.5,12.5,70,X,80,100,123,122,120,80,625,0,0,0,2,1,0,3,45,Medium Slow,1059860,Monster,Grass,20,NaN,NaN,6.0
4,1526,3,Venusaur,Seed Pokémon,Gigantamax,3.0,NaN,24.0,0.0,Grass,Poison,Overgrow,Powers up Grass-type moves when the Pokémon's ...,NaN,NaN,Chlorophyll,Boosts the Pokémon's Speed stat in harsh sunli...,NaN,NaN,87.5,12.5,50,Sword,80,82,83,100,100,80,525,0,0,0,2,1,0,3,45,Medium Slow,1059860,Monster,Grass,20,NaN,NaN,8.0

In [21]:
generation_map = {
    'Red': 1, 'Blue': 1, 'Green': 1, 'Yellow': 1,
    'Gold': 2, 'Silver': 2, 'Crystal': 2, 
    'Ruby': 3, 'Sapphire': 3, 'Emerald': 3, 'Fire Red': 3, 'Leaf Green': 3,
    'Diamond': 4, 'Pearl': 4, 'Platinum': 4, 'HeartGold' : 4,  'SoulSilver': 4, 
    'Black': 5, 'White': 5, 'Black 2': 5, 'White 2': 5,
    'X': 6, 'Y': 6, 'Omega Ruby': 6, 'Alpha Sapphire': 6,
    'Sun': 7, 'Moon': 7, 'Ultra Sun': 7, 'Ultra Moon': 7, "Let's Go Pikachu": 7, "Let's Go Eevee": 7, 
    'Sword': 8, 'Shield': 8, 'Brilliant Diamond': 8, 'Shining Pearl': 8, 'Legends Arceus': 8,
    'Scarlet': 9, 'Violet': 9
}

pokemon_database['generation'] = pokemon_database['Game(s) of Origin'].map(generation_map)

Adjusting the move names to enhance keep the same pattern

In [584]:
df_moves['move_name'] = df_moves['name'].str.replace(' ', '-', regex=False).str.lower()

Example of joining the move tables

In [585]:
pikachu = moves_pokemon('pikachu') 
pikachu_scarlet_violet = pikachu[pikachu['origin']=='scarlet-violet']

pikachu_moves = pikachu_scarlet_violet.merge(df_moves[['move_name', 'type', 'category', 'power', 'accuracy', 'pp', 'priority']], on='move_name', how='left')

In [586]:
pikachu_moves

,move_name,level_learned_at,move_learn_method,origin,type,category,power,accuracy,pp,priority
0,thunder-punch,0,machine,scarlet-violet,electric,physical,75.0,100.0,15.0,0
1,body-slam,0,machine,scarlet-violet,normal,physical,85.0,100.0,15.0,0
2,take-down,0,machine,scarlet-violet,normal,physical,90.0,85.0,20.0,0
3,tail-whip,1,level-up,scarlet-violet,normal,status,NaN,100.0,30.0,0
4,growl,1,level-up,scarlet-violet,normal,status,NaN,100.0,40.0,0
...,...,...,...,...,...,...,...,...,...,...
62,nuzzle,1,level-up,scarlet-violet,electric,physical,20.0,100.0,20.0,0
63,tera-blast,0,machine,scarlet-violet,normal,special,80.0,100.0,10.0,0
64,trailblaze,0,machine,scarlet-violet,grass,physical,50.0,100.0,20.0,0
65,alluring-voice,0,machine,scarlet-violet,fairy,special,80.0,100.0,10.0,0
66,upper-hand,0,machine,scarlet-violet,fighting,physical,65.0,100.0,15.0,3

# Visualization

## Per Pokemon

### Weakness

In [259]:
def pokemon_types(df, pokemon_name, pokemon_alternate_form=None):
    
    if pokemon_alternate_form:
        
        pokemon_types = df[(df['Pokemon Name']==pokemon_name) & (pokemon_database['Alternate Form Name']==pokemon_alternate_form)][['Primary Type', 'Secondary Type']]
        
        primary_type = pokemon_types.iloc[0]['Primary Type']
        
        secondary_type = pokemon_types.iloc[0]['Secondary Type']
    
    else:
        
        pokemon_types = df[(df['Pokemon Name']==pokemon_name) & (pokemon_database['Alternate Form Name'].isnull())][['Primary Type', 'Secondary Type']]
        
        primary_type = pokemon_types.iloc[0]['Primary Type']
        
        secondary_type = pokemon_types.iloc[0]['Secondary Type']
        
    if pd.isnull(secondary_type):
        
        return [primary_type]
    
    else:
        return [primary_type, secondary_type]
        
        
    return [primary_type, secondary_type]

In [326]:
 def weakeness_pokemon(df_type_charts, df_pokemon_database, pokemon_name, pokemon_alternate_form=None):
    
    types = pokemon_types(df_pokemon_database, pokemon_name, pokemon_alternate_form) 

    merged_results = None

    for i, pokemon_type in enumerate(types):

        filtered_data = df_type_charts[df_type_charts['Defense Type'] == pokemon_type].drop(columns=['Key'])

        if i == 0:
            filtered_data = filtered_data.rename(columns={'Defense Type': 'Defense Type (Primary)', 
                                                          'Multiplier': 'Multiplier (Primary)'})

        else:
            filtered_data = filtered_data.rename(columns={'Defense Type': 'Defense Type (Secondary)', 
                                                          'Multiplier': 'Multiplier (Secondary)'})


        if merged_results is None:

            merged_results = filtered_data
            
            merged_results['Weakness'] = merged_results['Multiplier (Primary)']

        else:

            merged_results = pd.merge(merged_results, filtered_data, on='Attacking', how='left')
            
            merged_results['Weakness'] = merged_results['Multiplier (Primary)'] * merged_results['Multiplier (Secondary)']
        
        cols = [col for col in merged_results.columns if col != 'Weakness']
        
        merged_results = merged_results[cols + ['Weakness']]
        
    conditions = [
        (merged_results['Weakness'] == 0),
        (merged_results['Weakness'] == 0.25),
        (merged_results['Weakness'] == 0.5),  
        (merged_results['Weakness'] == 1),
        (merged_results['Weakness'] == 2),
        (merged_results['Weakness'] == 4)
    ]

    categories = ['No Effect', 'Resistant (0.25)', 'Resistant (0.5)', 'Neutral', 'Super Effective (2)', 'Super Effective (4)']

    merged_results['Weakness Category'] = np.select(conditions, categories, default='Unknown')

    df_weakness_category_final = merged_results.groupby('Weakness Category').agg(
            count=('Weakness Category', 'size'),
            Attacking=('Attacking', lambda x: list(x))
        ).reset_index()
    
    return df_weakness_category_final

In [327]:
weakeness_pokemon(types_chart_final, pokemon_database, 'Charizard', 'Mega Y')

,Weakness Category,count,Attacking
0,Neutral,8,"[Normal, Ice, Poison, Flying, Psychic, Ghost, ..."
1,No Effect,1,[Ground]
2,Resistant (0.25),2,"[Grass, Bug]"
3,Resistant (0.5),4,"[Fire, Fighting, Steel, Fairy]"
4,Super Effective (2),2,"[Water, Electric]"
5,Super Effective (4),1,[Rock]

In [328]:
weakeness_pokemon(types_chart_final, pokemon_database, 'Zapdos')

,Weakness Category,count,Attacking
0,Neutral,10,"[Normal, Fire, Water, Electric, Poison, Psychi..."
1,No Effect,1,[Ground]
2,Resistant (0.5),5,"[Grass, Fighting, Flying, Bug, Steel]"
3,Super Effective (2),2,"[Ice, Rock]"

In [331]:
def bar_plot_weakness_category (df_weakeness_pokemon):
    
    order_list = ['Neutral', 'No Effect', 'Resistant (0.25)', 'Resistant (0.5)', 'Super Effective (2)', 'Super Effective (4)']

    custom_palette = ['#1f77b4', '#d3d3d3', '#2ca02c', '#006400', '#ff6347', '#b22222']

    fig = px.bar(
        df_weakeness_pokemon,
        x='Weakness Category',
        y='count',
        color='Weakness Category',
        title="Weakness Categories",
        labels={'count': 'Count'},
        hover_data={'Attacking'},
        category_orders={'Weakness Category': order_list},
        color_discrete_map={'Neutral': custom_palette[0], 'No Effect': custom_palette[1],
                           'Resistant (0.25)': custom_palette[2], 'Resistant (0.5)': custom_palette[3],
                           'Super Effective (2)': custom_palette[4], 'Super Effective (4)': custom_palette[5]}
    )

    fig.update_layout(
        title={'x': 0.5, 'xanchor': 'center', 'y': 0.95},  
        font=dict(family="Arial", size=14),  
        yaxis=dict(tickformat=".0f", showgrid=True, gridcolor='gray', gridwidth=0.2, title=None), 
        xaxis=dict(title=None),
        plot_bgcolor='white',  
        height=600,  
        width=900,  
    )

    fig.show()

In [332]:
bar_plot_weakness_category (weakeness_pokemon(types_chart_final, pokemon_database, 'Zapdos'))

### Stats

In [618]:
def pokemon_stats(df_pokemon_database, pokemon_name, pokemon_alternate_form=None):
    
    if pokemon_alternate_form:
    
        df = df_pokemon_database[(df_pokemon_database['Pokemon Name']==pokemon_name) & (df_pokemon_database['Alternate Form Name']==pokemon_alternate_form)][['Health Stat', 'Attack Stat', 'Defense Stat', 'Special Attack Stat', 'Special Defense Stat', 'Speed Stat', 'Base Stat Total']]

        df_melted = df.melt(var_name='Stat', value_name='Value')

        df_melted['Stat'] = df_melted['Stat'].str.replace(' Stat$', '', regex=True)
    
    else:
        
        df = df_pokemon_database[(df_pokemon_database['Pokemon Name']==pokemon_name) & (df_pokemon_database['Alternate Form Name'].isnull())][['Health Stat', 'Attack Stat', 'Defense Stat', 'Special Attack Stat', 'Special Defense Stat', 'Speed Stat', 'Base Stat Total']]
        
        df_melted = df.melt(var_name='Stat', value_name='Value')

        df_melted['Stat'] = df_melted['Stat'].str.replace(' Stat$', '', regex=True)
        
    return df_melted

In [348]:
pokemon_stats(pokemon_database, 'Charizard')

              Stat  Value
0           Health     78
1           Attack     84
2          Defense     78
3   Special Attack    109
4  Special Defense     85
5            Speed    100
6  Base Stat Total    534

In [368]:
def bar_plot_pokemon_stat (df_pokemon_database, pokemon_name, pokemon_alternate_form=None):
    
    df_pokemon_stat = pokemon_stats(pokemon_database, pokemon_name, pokemon_alternate_form)

    order_list = ['Health', 'Attack', 'Defense', 'Special Attack', 'Special Defense', 'Speed']

    custom_palette = {
        'Health': '#15f50e',           
        'Attack': '#ffeb3b',           
        'Defense': '#f5890e',          
        'Special Attack': '#3c91dc',   
        'Special Defense': '#6d0ef5',  
        'Speed': '#f06292'
    }

    fig = px.bar(
            df_pokemon_stat[df_pokemon_stat['Stat']!='Base Stat Total'],
            x='Value',
            y='Stat',
            title="Stats",
            labels={'count': 'Count'},
            color='Stat',
            category_orders={'Stat': order_list},
            color_discrete_map=custom_palette,
            text='Value'
        )

    fig.update_layout(
            title={'x': 0.5, 'xanchor': 'center', 'y': 0.95},  
            font=dict(family="Arial", size=14),  
            yaxis=dict(title=None, showgrid=False), 
            xaxis=dict(title=None, showticklabels=False),
            plot_bgcolor='white',  
            height=600,  
            width=900,  
        )

    fig.update_traces(textposition='outside')

    fig.show()

In [371]:
bar_plot_pokemon_stat(pokemon_database, 'Charizard')

### Moves

In [615]:
def pokemon_all_moves (pokemon_name, origin_game, df_moves_dataset):
    
    df_pokemon_moves = moves_pokemon(pokemon_name) 

    df_pokemon_moves_origin = df_pokemon_moves[df_pokemon_moves['origin']==origin_game]

    df_pokemon_moves_final = df_pokemon_moves_origin.merge(df_moves_dataset[['move_name', 'type', 'category', 'power', 'accuracy', 'pp', 'priority']], on='move_name', how='left')
    
    return df_pokemon_moves_final

In [617]:
pokemon_all_moves ('Umbreon', 'heartgold-soulsilver', df_moves)

,move_name,level_learned_at,move_learn_method,origin,type,category,power,accuracy,pp,priority
0,cut,0,machine,heartgold-soulsilver,normal,physical,50.0,95.0,30.0,0
1,sand-attack,8,level-up,heartgold-soulsilver,ground,status,NaN,100.0,15.0,0
2,headbutt,0,tutor,heartgold-soulsilver,normal,physical,70.0,100.0,15.0,0
3,tackle,1,level-up,heartgold-soulsilver,normal,physical,40.0,100.0,35.0,0
4,tail-whip,1,level-up,heartgold-soulsilver,normal,status,NaN,100.0,30.0,0
5,hyper-beam,0,machine,heartgold-soulsilver,normal,special,150.0,90.0,5.0,0
6,dig,0,machine,heartgold-soulsilver,ground,physical,80.0,100.0,10.0,0
7,toxic,0,machine,heartgold-soulsilver,poison,status,NaN,90.0,10.0,0
8,psychic,0,machine,heartgold-soulsilver,psychic,special,90.0,100.0,10.0,0
9,quick-attack,22,level-up,heartgold-soulsilver,normal,physical,40.0,100.0,30.0,1
10,screech,64,level-up,heartgold-soulsilver,normal,status,NaN,85.0,40.0,0
11,double-team,0,machine,heartgold-soulsilver,normal,status,NaN,NaN,15.0,0
12,confuse-ray,29,level-up,heartgold-soulsilver,ghost,status,NaN,100.0,10.0,0
13,swift,0,tutor,heartgold-soulsilver,normal,special,60.0,101.0,20.0,0
14,dream-eater,0,machine,heartgold-soulsilver,psychic,special,100.0,100.0,15.0,0
15,flash,0,machine,heartgold-soulsilver,normal,status,NaN,100.0,20.0,0
16,rest,0,machine,heartgold-soulsilver,psychic,status,NaN,NaN,5.0,0
17,substitute,0,machine,heartgold-soulsilver,normal,status,NaN,NaN,10.0,0
18,snore,0,tutor,heartgold-soulsilver,normal,special,50.0,100.0,15.0,0
19,spite,0,tutor,heartgold-soulsilver,ghost,status,NaN,100.0,10.0,0
20,protect,0,machine,heartgold-soulsilver,normal,status,NaN,NaN,10.0,4
21,feint-attack,36,level-up,heartgold-soulsilver,dark,physical,60.0,101.0,20.0,0
22,mud-slap,0,tutor,heartgold-soulsilver,ground,special,20.0,100.0,10.0,0
23,endure,0,machine,heartgold-soulsilver,normal,status,NaN,NaN,10.0,4
24,swagger,0,machine,heartgold-soulsilver,normal,status,NaN,85.0,15.0,0
25,mean-look,57,level-up,heartgold-soulsilver,normal,status,NaN,NaN,5.0,0
26,attract,0,machine,heartgold-soulsilver,normal,status,NaN,100.0,15.0,0
27,sleep-talk,0,machine,heartgold-soulsilver,normal,status,NaN,NaN,10.0,0
28,heal-bell,0,tutor,heartgold-soulsilver,normal,status,NaN,NaN,5.0,0
29,return,0,machine,heartgold-soulsilver,normal,physical,NaN,100.0,20.0,0
30,frustration,0,machine,heartgold-soulsilver,normal,physical,NaN,100.0,20.0,0
31,pursuit,15,level-up,heartgold-soulsilver,dark,physical,40.0,100.0,20.0,0
32,iron-tail,0,machine,heartgold-soulsilver,steel,physical,100.0,75.0,15.0,0
33,moonlight,71,level-up,heartgold-soulsilver,fairy,status,NaN,NaN,5.0,0
34,hidden-power,0,machine,heartgold-soulsilver,normal,special,60.0,100.0,15.0,0
35,rain-dance,0,machine,heartgold-soulsilver,water,status,NaN,NaN,5.0,0
36,sunny-day,0,machine,heartgold-soulsilver,fire,status,NaN,NaN,5.0,0
37,psych-up,0,machine,heartgold-soulsilver,normal,status,NaN,NaN,10.0,0
38,shadow-ball,0,machine,heartgold-soulsilver,ghost,special,80.0,100.0,15.0,0
39,torment,0,machine,heartgold-soulsilver,dark,status,NaN,100.0,15.0,0
40,facade,0,machine,heartgold-soulsilver,normal,physical,70.0,100.0,20.0,0
41,taunt,0,machine,heartgold-soulsilver,dark,status,NaN,100.0,20.0,0
42,helping-hand,1,level-up,heartgold-soulsilver,normal,status,NaN,NaN,20.0,5
43,helping-hand,0,tutor,heartgold-soulsilver,normal,status,NaN,NaN,20.0,5
44,snatch,0,machine,heartgold-soulsilver,dark,status,NaN,NaN,10.0,4
45,secret-power,0,machine,heartgold-soulsilver,normal,physical,70.0,100.0,20.0,0
46,natural-gift,0,machine,heartgold-soulsilver,normal,physical,NaN,100.0,15.0,0
47,payback,0,machine,heartgold-soulsilver,dark,physical,50.0,100.0,10.0,0
48,assurance,43,level-up,heartgold-soulsilver,dark,physical,60.0,100.0,10.0,0
49,guard-swap,78,level-up,heartgold-soulsilver,psychic,status,NaN,NaN,10.0,0
50,last-resort,50,level-up,heartgold-soulsilver,normal,physical,140.0,100.0,5.0,0
51,last-resort,0,tutor,heartgold-soulsilver,normal,physical,140.0,100.0,5.0,0
52,sucker-punch,0,tutor,heartgold-soulsilver,dark,physical,70.0,100.0,5.0,1
53,dark-pulse,0,machine,heartgold-soulsilver,dark,special,80.0,100.0,15.0,0
54,giga-impact,0,machine,heartgold-soulsilver,normal,physical,150.0,90.0,5.0,0
55,captivate,0,machine,heartgold-soulsilver,normal,status,NaN,100.0,20.0,0

In [659]:
def calculate_damage(df):
    
    attack = np.where(df['category'] == 'physical', df['Attack Stat'],
                      np.where(df['category'] == 'special', df['Special Attack Stat'], np.nan))

    stab = np.where((df['type'] == df['Primary Type']) | (df['type'] == df['Secondary Type']), 1.5, 1)

    base_damage = np.where(df['power'].notna(), (df['power'] * attack) * stab, np.nan)

    return base_damage

def best_moves_pokemon (df_pokemon_database, df_moves, pokemon_name, origin, pokemon_alternate_form=None, level_learned_at=None,
                        move_learn_method=None, move_type=None, move_category=None, accuracy=None, move_pp=None):
    
    df_pokemon_all_moves = pokemon_all_moves (pokemon_name, origin, df_moves)
    
    if pokemon_alternate_form:
    
        pokemon_name_database = df_pokemon_database[(df_pokemon_database['Pokemon Name']==pokemon_name)\
                                                  & (df_pokemon_database['Alternate Form Name']==pokemon_alternate_form)]\
                                                    [['Primary Type', 'Secondary Type', 'Health Stat', 'Attack Stat',\
                                                      'Defense Stat', 'Special Attack Stat', 'Special Defense Stat',\
                                                      'Speed Stat', 'Base Stat Total']]
    
    else:
        
        pokemon_name_database = df_pokemon_database[(df_pokemon_database['Pokemon Name']==pokemon_name)\
                                                  & (df_pokemon_database['Alternate Form Name'].isnull())]\
                                                    [['Primary Type', 'Secondary Type', 'Health Stat', 'Attack Stat',\
                                                      'Defense Stat', 'Special Attack Stat', 'Special Defense Stat',\
                                                      'Speed Stat', 'Base Stat Total']]
        
    df_pokemon_all_moves['key'] = 1
    pokemon_name_database['key'] = 1

    df_final = pd.merge(df_pokemon_all_moves, pokemon_name_database, on='key').drop('key', axis=1)                          
    
    df_final['move_damage'] = calcular_dano_vetorizado(df_final)
    
    filtros = []
    
    if level_learned_at is not None:
        filtros.append(df_final['level_learned_at'] >= level_learned_at)
        
    if move_learn_method is not None:
        filtros.append(df_final['move_learn_method'] == move_learn_method)
        
    if move_type is not None:
        filtros.append(df_final['type'] == move_type)
        
    if move_category is not None:
        filtros.append(df_final['category'] == move_category)
        
    if accuracy is not None:
        filtros.append(df_final['accuracy'] >= accuracy)
        
    if move_pp is not None:
        filtros.append(df_final['pp'] >= move_pp)
    
    if filtros:
        df_final = df_final[np.logical_and.reduce(filtros)]
        
    
    df_final = df_final[['move_name', 'move_damage', 'level_learned_at', 'move_learn_method', 'origin', 'type',
                         'category', 'power', 'accuracy', 'pp', 'priority']]
    
    df_final = df_final.sort_values(by='move_damage', ascending=False).reset_index(drop=True)
    
    return df_final

In [660]:
best_moves_pokemon = best_moves_pokemon (pokemon_database, df_moves, 'Umbreon', 'heartgold-soulsilver', pokemon_alternate_form=None, level_learned_at=None,
                        move_learn_method=None, move_type=None, move_category=None, accuracy=90, move_pp=10)

best_moves_pokemon

,move_name,move_damage,level_learned_at,move_learn_method,origin,type,category,power,accuracy,pp,priority
0,dream-eater,6000.0,0,machine,heartgold-soulsilver,psychic,special,100.0,100.0,15.0,0
1,psychic,5400.0,0,machine,heartgold-soulsilver,psychic,special,90.0,100.0,10.0,0
2,dig,5200.0,0,machine,heartgold-soulsilver,ground,physical,80.0,100.0,10.0,0
3,dark-pulse,4800.0,0,machine,heartgold-soulsilver,dark,special,80.0,100.0,15.0,0
4,shadow-ball,4800.0,0,machine,heartgold-soulsilver,ghost,special,80.0,100.0,15.0,0
5,headbutt,4550.0,0,tutor,heartgold-soulsilver,normal,physical,70.0,100.0,15.0,0
6,secret-power,4550.0,0,machine,heartgold-soulsilver,normal,physical,70.0,100.0,20.0,0
7,facade,4550.0,0,machine,heartgold-soulsilver,normal,physical,70.0,100.0,20.0,0
8,assurance,3900.0,43,level-up,heartgold-soulsilver,dark,physical,60.0,100.0,10.0,0
9,feint-attack,3900.0,36,level-up,heartgold-soulsilver,dark,physical,60.0,101.0,20.0,0
10,hidden-power,3600.0,0,machine,heartgold-soulsilver,normal,special,60.0,100.0,15.0,0
11,swift,3600.0,0,tutor,heartgold-soulsilver,normal,special,60.0,101.0,20.0,0
12,payback,3250.0,0,machine,heartgold-soulsilver,dark,physical,50.0,100.0,10.0,0
13,cut,3250.0,0,machine,heartgold-soulsilver,normal,physical,50.0,95.0,30.0,0
14,snore,3000.0,0,tutor,heartgold-soulsilver,normal,special,50.0,100.0,15.0,0
15,pursuit,2600.0,15,level-up,heartgold-soulsilver,dark,physical,40.0,100.0,20.0,0
16,quick-attack,2600.0,22,level-up,heartgold-soulsilver,normal,physical,40.0,100.0,30.0,1
17,tackle,2600.0,1,level-up,heartgold-soulsilver,normal,physical,40.0,100.0,35.0,0
18,mud-slap,1200.0,0,tutor,heartgold-soulsilver,ground,special,20.0,100.0,10.0,0
19,sand-attack,NaN,8,level-up,heartgold-soulsilver,ground,status,NaN,100.0,15.0,0
20,tail-whip,NaN,1,level-up,heartgold-soulsilver,normal,status,NaN,100.0,30.0,0
21,toxic,NaN,0,machine,heartgold-soulsilver,poison,status,NaN,90.0,10.0,0
22,confuse-ray,NaN,29,level-up,heartgold-soulsilver,ghost,status,NaN,100.0,10.0,0
23,flash,NaN,0,machine,heartgold-soulsilver,normal,status,NaN,100.0,20.0,0
24,spite,NaN,0,tutor,heartgold-soulsilver,ghost,status,NaN,100.0,10.0,0
25,attract,NaN,0,machine,heartgold-soulsilver,normal,status,NaN,100.0,15.0,0
26,return,NaN,0,machine,heartgold-soulsilver,normal,physical,NaN,100.0,20.0,0
27,frustration,NaN,0,machine,heartgold-soulsilver,normal,physical,NaN,100.0,20.0,0
28,torment,NaN,0,machine,heartgold-soulsilver,dark,status,NaN,100.0,15.0,0
29,taunt,NaN,0,machine,heartgold-soulsilver,dark,status,NaN,100.0,20.0,0
30,natural-gift,NaN,0,machine,heartgold-soulsilver,normal,physical,NaN,100.0,15.0,0
31,captivate,NaN,0,machine,heartgold-soulsilver,normal,status,NaN,100.0,20.0,0

## Per Types

### Weakness

#### Offense

In [532]:
def get_multiplier(df, attack_type, defense_type):
    
    row = df[(df['Attacking'] == attack_type) & (df['Defense Type'] == defense_type)]
    
    if not row.empty:
        
        return row['Multiplier'].values[0]
    
    return 1.0

def final_types_combination(df_types_chart_final):

    unique_types = df_types_chart_final['Attacking'].unique()

    type_combinations = [comb for comb in itertools.combinations(unique_types, 2)]

    combination_data = []

    for type1, type2 in type_combinations:

        for attack_type in unique_types:

            multiplier1 = get_multiplier(df_types_chart_final, attack_type, type1)
            multiplier2 = get_multiplier(df_types_chart_final, attack_type, type2)
            total_multiplier = multiplier1 * multiplier2

            combination_data.append({
                'Attack Type': attack_type,
                'Defensive Type 1': type1,
                'Defensive Type 2': type2,
                'Multiplier': total_multiplier
            })

    df_combinations = pd.DataFrame(combination_data)
    
    df_single_types = df_types_chart_final.rename(columns={'Defense Type': 'Defensive Type 1', 'Attacking': 'Attack Type'}).drop(columns=['Key'])
    
    df_single_types['Defensive Type 2'] = np.nan
    
    df_combined = pd.concat([df_single_types, df_combinations], ignore_index=True)
    
    df_combined = df_combined[['Attack Type', 'Defensive Type 1', 'Defensive Type 2', 'Multiplier']]
    
    return df_combined

In [533]:
df_final_types_combinations = final_types_combination(types_chart_final)

In [534]:
df_final_types_combinations

     Attack Type Defensive Type 1 Defensive Type 2  Multiplier
0         Normal           Normal              NaN         1.0
1           Fire           Normal              NaN         1.0
2          Water           Normal              NaN         1.0
3       Electric           Normal              NaN         1.0
4          Grass           Normal              NaN         1.0
...          ...              ...              ...         ...
3073       Ghost            Steel            Fairy         1.0
3074      Dragon            Steel            Fairy         0.0
3075        Dark            Steel            Fairy         0.5
3076       Steel            Steel            Fairy         1.0
3077       Fairy            Steel            Fairy         0.5

[3078 rows x 4 columns]

In [535]:
def table_types_categories (df):
    
    conditions = [
        (df['Multiplier'] == 0),
        (df['Multiplier'] == 0.25),
        (df['Multiplier'] == 0.5),  
        (df['Multiplier'] == 1),
        (df['Multiplier'] == 2),
        (df['Multiplier'] == 4)
    ]

    categories = ['No Effect', 'Resistant (0.25)', 'Resistant (0.5)', 'Neutral', 'Super Effective (2)', 'Super Effective (4)']

    df['Weakness Category'] = np.select(conditions, categories, default='Unknown')

    df['Defensive Type'] = df.apply(
        lambda row: f"{row['Defensive Type 1']}/{row['Defensive Type 2']}" if pd.notna(row['Defensive Type 1']) and pd.notna(row['Defensive Type 2']) 
        else row['Defensive Type 1'] if pd.notna(row['Defensive Type 1']) 
        else row['Defensive Type 2'] if pd.notna(row['Defensive Type 2']) 
        else '', axis=1
    )
    
    return df

In [536]:
df_table_types_categories = table_types_categories (df_final_types_combinations)

In [537]:
df_table_types_categories

,Attack Type,Defensive Type 1,Defensive Type 2,Multiplier,Weakness Category,Defensive Type
0,Normal,Normal,NaN,1.0,Neutral,Normal
1,Fire,Normal,NaN,1.0,Neutral,Normal
2,Water,Normal,NaN,1.0,Neutral,Normal
3,Electric,Normal,NaN,1.0,Neutral,Normal
4,Grass,Normal,NaN,1.0,Neutral,Normal
...,...,...,...,...,...,...
3073,Ghost,Steel,Fairy,1.0,Neutral,Steel/Fairy
3074,Dragon,Steel,Fairy,0.0,No Effect,Steel/Fairy
3075,Dark,Steel,Fairy,0.5,Resistant (0.5),Steel/Fairy
3076,Steel,Steel,Fairy,1.0,Neutral,Steel/Fairy
3077,Fairy,Steel,Fairy,0.5,Resistant (0.5),Steel/Fairy

In [538]:
def groupby_categories_attacking (df):
    
    df_groupby = df.groupby(['Attack Type', 'Weakness Category']).agg(
        Count=('Weakness Category', 'size'),
        Defensive_Type=('Defensive Type', lambda x: list(x))
    ).reset_index()
    
    df_groupby = df_groupby.rename(columns={'Defensive_Type': 'Defensive Type'})
    
    return df_groupby

In [539]:
table_categories_attacking = groupby_categories_attacking (df_table_types_categories)

In [540]:
table_categories_attacking

,Attack Type,Weakness Category,Count,Defensive Type
0,Bug,Neutral,57,"[Normal, Water, Electric, Ice, Ground, Bug, Rock, Dragon, Normal/Water, Normal/Electric, Normal/Ice, Normal/Ground, Normal/Bug, Normal/Rock, Normal/Dragon, Fire/Grass, Fire/Psychic, Fire/Dark, Water/Electric, Water/Ice, Water/Ground, Water/Bug, Water/Rock, Water/Dragon, Electric/Ice, Electric/Ground, Electric/Bug, Electric/Rock, Electric/Dragon, Grass/Fighting, Grass/Poison, Grass/Flying, Grass/Ghost, Grass/Steel, Grass/Fairy, Ice/Ground, Ice/Bug, Ice/Rock, Ice/Dragon, Fighting/Psychic, Fighting/Dark, Poison/Psychic, Poison/Dark, Ground/Bug, Ground/Rock, Ground/Dragon, Flying/Psychic, Flying/Dark, Psychic/Ghost, Psychic/Steel, Psychic/Fairy, Bug/Rock, Bug/Dragon, Rock/Dragon, Ghost/Dark, Dark/Steel, Dark/Fairy]"
1,Bug,Resistant (0.25),21,"[Fire/Fighting, Fire/Poison, Fire/Flying, Fire/Ghost, Fire/Steel, Fire/Fairy, Fighting/Poison, Fighting/Flying, Fighting/Ghost, Fighting/Steel, Fighting/Fairy, Poison/Flying, Poison/Ghost, Poison/Steel, Poison/Fairy, Flying/Ghost, Flying/Steel, Flying/Fairy, Ghost/Steel, Ghost/Fairy, Steel/Fairy]"
2,Bug,Resistant (0.5),63,"[Fire, Fighting, Poison, Flying, Ghost, Steel, Fairy, Normal/Fire, Normal/Fighting, Normal/Poison, Normal/Flying, Normal/Ghost, Normal/Steel, Normal/Fairy, Fire/Water, Fire/Electric, Fire/Ice, Fire/Ground, Fire/Bug, Fire/Rock, Fire/Dragon, Water/Fighting, Water/Poison, Water/Flying, Water/Ghost, Water/Steel, Water/Fairy, Electric/Fighting, Electric/Poison, Electric/Flying, Electric/Ghost, Electric/Steel, Electric/Fairy, Ice/Fighting, Ice/Poison, Ice/Flying, Ice/Ghost, Ice/Steel, Ice/Fairy, Fighting/Ground, Fighting/Bug, Fighting/Rock, Fighting/Dragon, Poison/Ground, Poison/Bug, Poison/Rock, Poison/Dragon, Ground/Flying, Ground/Ghost, Ground/Steel, Ground/Fairy, Flying/Bug, Flying/Rock, Flying/Dragon, Bug/Ghost, Bug/Steel, Bug/Fairy, Rock/Ghost, Rock/Steel, Rock/Fairy, Ghost/Dragon, Dragon/Steel, Dragon/Fairy]"
3,Bug,Super Effective (2),27,"[Grass, Psychic, Dark, Normal/Grass, Normal/Psychic, Normal/Dark, Water/Grass, Water/Psychic, Water/Dark, Electric/Grass, Electric/Psychic, Electric/Dark, Grass/Ice, Grass/Ground, Grass/Bug, Grass/Rock, Grass/Dragon, Ice/Psychic, Ice/Dark, Ground/Psychic, Ground/Dark, Psychic/Bug, Psychic/Rock, Psychic/Dragon, Bug/Dark, Rock/Dark, Dragon/Dark]"
4,Bug,Super Effective (4),3,"[Grass/Psychic, Grass/Dark, Psychic/Dark]"
...,...,...,...,...
88,Water,Neutral,87,"[Normal, Electric, Ice, Fighting, Poison, Flying, Psychic, Bug, Ghost, Dark, Steel, Fairy, Normal/Electric, Normal/Ice, Normal/Fighting, Normal/Poison, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Ghost, Normal/Dark, Normal/Steel, Normal/Fairy, Fire/Water, Fire/Grass, Fire/Dragon, Water/Ground, Water/Rock, Electric/Ice, Electric/Fighting, Electric/Poison, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Ghost, Electric/Dark, Electric/Steel, Electric/Fairy, Grass/Ground, Grass/Rock, Ice/Fighting, Ice/Poison, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Ghost, Ice/Dark, Ice/Steel, Ice/Fairy, Fighting/Poison, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Ghost, Fighting/Dark, Fighting/Steel, Fighting/Fairy, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Ghost, Poison/Dark, Poison/Steel, Poison/Fairy, Ground/Dragon, Flying/Psychic, Flying/Bug, Flying/Ghost, Flying/Dark, Flying/Steel, Flying/Fairy, Psychic/Bug, Psychic/Ghost, Psychic/Dark, Psychic/Steel, Psychic/Fairy, Bug/Ghost, Bug/Dark, Bug/Steel, Bug/Fairy, Rock/Dragon, Ghost/Dark, Ghost/Steel, Ghost/Fairy, Dark/Steel, Dark/Fairy, Steel/Fairy]"
89,Water,Resistant (0.25),3,"[Water/Grass, Water/Dragon, Grass/Dragon]"
90,Water,Resistant (0.5),39,"[Water, Grass, Dragon, Normal/Water, Normal/Grass, Normal/Dragon, Water/Electric, Water/Ice, Water/Fighting, Water/Poison, Water/Flying, Water/Psychic, Water/Bug, Water/Ghost, Water/Dark, Water/Steel, Water/Fairy, Electric/Grass, Electric/Dragon, Grass/Ice, Grass/Fighting, Grass/Poison, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Ghost, Grass/Dark, Grass/Steel, Grass/Fairy, Ice/Dragon, Fighting/Dragon, Poison/Dragon, Flying/Dragon, Psychic/Dragon, Bug/Dragon, Ghost/Dragon, Dragon/Dark, Dragon/Steel, Dragon/Fairy]"
91,Water,Super Effective (2),39,"[Fire, Ground, Rock, Normal/Fire, Normal/Ground, Normal/Rock, Fire/Electric, Fire/Ice, Fire/Fighting, Fire/Poison, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Ghost, Fire/Dark, Fire/Steel, Fire/Fairy, Electric/Ground, Electric/Rock, Ice/Ground, Ice/Rock, Fighting/Ground, Fighting/Rock, Poison/Ground, Poison/Rock, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Ghost, Ground/Dark, Ground/Steel, Ground/Fairy, Flying/Rock, Psychic/Rock, Bug/Rock, Rock/Ghost, Rock/Dark, Rock/Steel, Rock/Fairy]"
92,Water,Super Effective (4),3,"[Fire/Ground, Fire/Rock, Ground/Rock]"

In [480]:
def attacking_types_category (df, weakness_category, ascending=False):
    
    df_sorted = df[df['Weakness Category']==weakness_category].sort_values(by='Count', ascending=ascending)
    
    return df_sorted

In [512]:
attacking_types_category (table_categories_attacking, 'No Effect', ascending=False)

,Attack Type,Weakness Category,Count,Defensive Type
11,Dragon,No Effect,18,"[Fairy, Normal/Fairy, Fire/Fairy, Water/Fairy, Electric/Fairy, Grass/Fairy, Ice/Fairy, Fighting/Fairy, Poison/Fairy, Ground/Fairy, Flying/Fairy, Psychic/Fairy, Bug/Fairy, Rock/Fairy, Ghost/Fairy, Dragon/Fairy, Dark/Fairy, Steel/Fairy]"
15,Electric,No Effect,18,"[Ground, Normal/Ground, Fire/Ground, Water/Ground, Electric/Ground, Grass/Ground, Ice/Ground, Fighting/Ground, Poison/Ground, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Rock, Ground/Ghost, Ground/Dragon, Ground/Dark, Ground/Steel, Ground/Fairy]"
26,Fighting,No Effect,18,"[Ghost, Normal/Ghost, Fire/Ghost, Water/Ghost, Electric/Ghost, Grass/Ghost, Ice/Ghost, Fighting/Ghost, Poison/Ghost, Ground/Ghost, Flying/Ghost, Psychic/Ghost, Bug/Ghost, Rock/Ghost, Ghost/Dragon, Ghost/Dark, Ghost/Steel, Ghost/Fairy]"
42,Ghost,No Effect,18,"[Normal, Normal/Fire, Normal/Water, Normal/Electric, Normal/Grass, Normal/Ice, Normal/Fighting, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Rock, Normal/Ghost, Normal/Dragon, Normal/Dark, Normal/Steel, Normal/Fairy]"
52,Ground,No Effect,18,"[Flying, Normal/Flying, Fire/Flying, Water/Flying, Electric/Flying, Grass/Flying, Ice/Flying, Fighting/Flying, Poison/Flying, Ground/Flying, Flying/Psychic, Flying/Bug, Flying/Rock, Flying/Ghost, Flying/Dragon, Flying/Dark, Flying/Steel, Flying/Fairy]"
63,Normal,No Effect,18,"[Ghost, Normal/Ghost, Fire/Ghost, Water/Ghost, Electric/Ghost, Grass/Ghost, Ice/Ghost, Fighting/Ghost, Poison/Ghost, Ground/Ghost, Flying/Ghost, Psychic/Ghost, Bug/Ghost, Rock/Ghost, Ghost/Dragon, Ghost/Dark, Ghost/Steel, Ghost/Fairy]"
67,Poison,No Effect,18,"[Steel, Normal/Steel, Fire/Steel, Water/Steel, Electric/Steel, Grass/Steel, Ice/Steel, Fighting/Steel, Poison/Steel, Ground/Steel, Flying/Steel, Psychic/Steel, Bug/Steel, Rock/Steel, Ghost/Steel, Dragon/Steel, Dark/Steel, Steel/Fairy]"
73,Psychic,No Effect,18,"[Dark, Normal/Dark, Fire/Dark, Water/Dark, Electric/Dark, Grass/Dark, Ice/Dark, Fighting/Dark, Poison/Dark, Ground/Dark, Flying/Dark, Psychic/Dark, Bug/Dark, Rock/Dark, Ghost/Dark, Dragon/Dark, Dark/Steel, Dark/Fairy]"

In [513]:
attacking_types_category (table_categories_attacking, 'Resistant (0.25)', ascending=False)

,Attack Type,Weakness Category,Count,Defensive Type
1,Bug,Resistant (0.25),21,"[Fire/Fighting, Fire/Poison, Fire/Flying, Fire/Ghost, Fire/Steel, Fire/Fairy, Fighting/Poison, Fighting/Flying, Fighting/Ghost, Fighting/Steel, Fighting/Fairy, Poison/Flying, Poison/Ghost, Poison/Steel, Poison/Fairy, Flying/Ghost, Flying/Steel, Flying/Fairy, Ghost/Steel, Ghost/Fairy, Steel/Fairy]"
47,Grass,Resistant (0.25),21,"[Fire/Grass, Fire/Poison, Fire/Flying, Fire/Bug, Fire/Dragon, Fire/Steel, Grass/Poison, Grass/Flying, Grass/Bug, Grass/Dragon, Grass/Steel, Poison/Flying, Poison/Bug, Poison/Dragon, Poison/Steel, Flying/Bug, Flying/Dragon, Flying/Steel, Bug/Dragon, Bug/Steel, Dragon/Steel]"
27,Fighting,Resistant (0.25),10,"[Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Fairy, Flying/Psychic, Flying/Bug, Flying/Fairy, Psychic/Bug, Psychic/Fairy, Bug/Fairy]"
32,Fire,Resistant (0.25),6,"[Fire/Water, Fire/Rock, Fire/Dragon, Water/Rock, Water/Dragon, Rock/Dragon]"
58,Ice,Resistant (0.25),6,"[Fire/Water, Fire/Ice, Fire/Steel, Water/Ice, Water/Steel, Ice/Steel]"
68,Poison,Resistant (0.25),6,"[Poison/Ground, Poison/Rock, Poison/Ghost, Ground/Rock, Ground/Ghost, Rock/Ghost]"
84,Steel,Resistant (0.25),6,"[Fire/Water, Fire/Electric, Fire/Steel, Water/Electric, Water/Steel, Electric/Steel]"
6,Dark,Resistant (0.25),3,"[Fighting/Dark, Fighting/Fairy, Dark/Fairy]"
16,Electric,Resistant (0.25),3,"[Electric/Grass, Electric/Dragon, Grass/Dragon]"
21,Fairy,Resistant (0.25),3,"[Fire/Poison, Fire/Steel, Poison/Steel]"
37,Flying,Resistant (0.25),3,"[Electric/Rock, Electric/Steel, Rock/Steel]"
79,Rock,Resistant (0.25),3,"[Fighting/Ground, Fighting/Steel, Ground/Steel]"
89,Water,Resistant (0.25),3,"[Water/Grass, Water/Dragon, Grass/Dragon]"
53,Ground,Resistant (0.25),1,[Grass/Bug]
64,Normal,Resistant (0.25),1,[Rock/Steel]
74,Psychic,Resistant (0.25),1,[Psychic/Steel]

In [514]:
attacking_types_category (table_categories_attacking, 'Resistant (0.5)', ascending=False)

,Attack Type,Weakness Category,Count,Defensive Type
2,Bug,Resistant (0.5),63,"[Fire, Fighting, Poison, Flying, Ghost, Steel, Fairy, Normal/Fire, Normal/Fighting, Normal/Poison, Normal/Flying, Normal/Ghost, Normal/Steel, Normal/Fairy, Fire/Water, Fire/Electric, Fire/Ice, Fire/Ground, Fire/Bug, Fire/Rock, Fire/Dragon, Water/Fighting, Water/Poison, Water/Flying, Water/Ghost, Water/Steel, Water/Fairy, Electric/Fighting, Electric/Poison, Electric/Flying, Electric/Ghost, Electric/Steel, Electric/Fairy, Ice/Fighting, Ice/Poison, Ice/Flying, Ice/Ghost, Ice/Steel, Ice/Fairy, Fighting/Ground, Fighting/Bug, Fighting/Rock, Fighting/Dragon, Poison/Ground, Poison/Bug, Poison/Rock, Poison/Dragon, Ground/Flying, Ground/Ghost, Ground/Steel, Ground/Fairy, Flying/Bug, Flying/Rock, Flying/Dragon, Bug/Ghost, Bug/Steel, Bug/Fairy, Rock/Ghost, Rock/Steel, Rock/Fairy, Ghost/Dragon, Dragon/Steel, Dragon/Fairy]"
48,Grass,Resistant (0.5),63,"[Fire, Grass, Poison, Flying, Bug, Dragon, Steel, Normal/Fire, Normal/Grass, Normal/Poison, Normal/Flying, Normal/Bug, Normal/Dragon, Normal/Steel, Fire/Electric, Fire/Ice, Fire/Fighting, Fire/Psychic, Fire/Ghost, Fire/Dark, Fire/Fairy, Electric/Grass, Electric/Poison, Electric/Flying, Electric/Bug, Electric/Dragon, Electric/Steel, Grass/Ice, Grass/Fighting, Grass/Psychic, Grass/Ghost, Grass/Dark, Grass/Fairy, Ice/Poison, Ice/Flying, Ice/Bug, Ice/Dragon, Ice/Steel, Fighting/Poison, Fighting/Flying, Fighting/Bug, Fighting/Dragon, Fighting/Steel, Poison/Psychic, Poison/Ghost, Poison/Dark, Poison/Fairy, Flying/Psychic, Flying/Ghost, Flying/Dark, Flying/Fairy, Psychic/Bug, Psychic/Dragon, Psychic/Steel, Bug/Ghost, Bug/Dark, Bug/Fairy, Ghost/Dragon, Ghost/Steel, Dragon/Dark, Dragon/Fairy, Dark/Steel, Steel/Fairy]"
69,Poison,Resistant (0.5),48,"[Poison, Ground, Rock, Ghost, Normal/Poison, Normal/Ground, Normal/Rock, Normal/Ghost, Fire/Poison, Fire/Ground, Fire/Rock, Fire/Ghost, Water/Poison, Water/Ground, Water/Rock, Water/Ghost, Electric/Poison, Electric/Ground, Electric/Rock, Electric/Ghost, Ice/Poison, Ice/Ground, Ice/Rock, Ice/Ghost, Fighting/Poison, Fighting/Ground, Fighting/Rock, Fighting/Ghost, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Dragon, Poison/Dark, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Dragon, Ground/Dark, Flying/Rock, Flying/Ghost, Psychic/Rock, Psychic/Ghost, Bug/Rock, Bug/Ghost, Rock/Dragon, Rock/Dark, Ghost/Dragon, Ghost/Dark]"
85,Steel,Resistant (0.5),48,"[Fire, Water, Electric, Steel, Normal/Fire, Normal/Water, Normal/Electric, Normal/Steel, Fire/Grass, Fire/Fighting, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Ghost, Fire/Dragon, Fire/Dark, Water/Grass, Water/Fighting, Water/Poison, Water/Ground, Water/Flying, Water/Psychic, Water/Bug, Water/Ghost, Water/Dragon, Water/Dark, Electric/Grass, Electric/Fighting, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Ghost, Electric/Dragon, Electric/Dark, Grass/Steel, Fighting/Steel, Poison/Steel, Ground/Steel, Flying/Steel, Psychic/Steel, Bug/Steel, Ghost/Steel, Dragon/Steel, Dark/Steel]"
33,Fire,Resistant (0.5),44,"[Fire, Water, Rock, Dragon, Normal/Fire, Normal/Water, Normal/Rock, Normal/Dragon, Fire/Electric, Fire/Fighting, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Psychic, Fire/Ghost, Fire/Dark, Fire/Fairy, Water/Electric, Water/Fighting, Water/Poison, Water/Ground, Water/Flying, Water/Psychic, Water/Ghost, Water/Dark, Water/Fairy, Electric/Rock, Electric/Dragon, Fighting/Rock, Fighting/Dragon, Poison/Rock, Poison/Dragon, Ground/Rock, Ground/Dragon, Flying/Rock, Flying/Dragon, Psychic/Rock, Psychic/Dragon, Rock/Ghost, Rock/Dark, Rock/Fairy, Ghost/Dragon, Dragon/Dark, Dragon/Fairy]"
59,Ice,Resistant (0.5),44,"[Fire, Water, Ice, Steel, Normal/Fire, Normal/Water, Normal/Ice, Normal/Steel, Fire/Electric, Fire/Fighting, Fire/Poison, Fire/Psychic, Fire/Bug, Fire/Rock, Fire/Ghost, Fire/Dark, Fire/Fairy, Water/Electric, Water/Fighting, Water/Poison, Water/Psychic, Water/Bug, Water/Rock, Water/Ghost, Water/Dark, Water/Fairy, Electric/Ice, Electric/Steel, Ice/Fighting, Ice/Poison, Ice/Psychic, Ice/Bug, Ice/Rock, Ice/Ghost, Ice/Dark, Ice/Fairy, Fighting/Steel, Poison/Steel, Psychic/Steel, Bug/Steel, Rock/Steel, Ghost/Steel, Dark/Steel, Steel/Fairy]"
7,Dark,Resistant (0.5),42,"[Fighting, Dark, Fairy, Normal/Fighting, Normal/Dark, Normal/Fairy, Fire/Fighting, Fire/Dark, Fire/Fairy, Water/Fighting, Water/Dark, Water/Fairy, Electric/Fighting, Electric/Dark, Electric/Fairy, Grass/Fighting, Grass/Dark, Grass/Fairy, Ice/Fighting, Ice/Dark, Ice/Fairy, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Bug, Fighting/Rock, Fighting/Dragon, Fighting/Steel, Poison/Dark, Poison/Fairy, Ground/Dark, Ground/Fairy, Flying/Dark, Flying/Fairy, Bug/Dark, Bug/Fairy, Rock/Dark, Rock/Fairy, Dragon/Dark, Dragon/Fairy, Dark/Steel, Steel/Fairy]"
28,Fighting,Resistant (0.5),40,"[Poison, Flying, Psychic, Bug, Fairy, Fire/Poison, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Fairy, Water/Poison, Water/Flying, Water/Psychic, Water/Bug, Water/Fairy, Electric/Poison, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Fairy, Grass/Poison, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Fairy, Fighting/Poison, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Fairy, Poison/Ground, Poison/Dragon, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Fairy, Flying/Dragon, Psychic/Dragon, Bug/Dragon, Dragon/Fairy]"
17,Electric,Resistant (0.5),39,"[Electric, Grass, Dragon, Normal/Electric, Normal/Grass, Normal/Dragon, Fire/Electric, Fire/Grass, Fire/Dragon, Electric/Ice, Electric/Fighting, Electric/Poison, Electric/Psychic, Electric/Bug, Electric/Rock, Electric/Ghost, Electric/Dark, Electric/Steel, Electric/Fairy, Grass/Ice, Grass/Fighting, Grass/Poison, Grass/Psychic, Grass/Bug, Grass/Rock, Grass/Ghost, Grass/Dark, Grass/Steel, Grass/Fairy, Ice/Dragon, Fighting/Dragon, Poison/Dragon, Psychic/Dragon, Bug/Dragon, Rock/Dragon, Ghost/Dragon, Dragon/Dark, Dragon/Steel, Dragon/Fairy]"
22,Fairy,Resistant (0.5),39,"[Fire, Poison, Steel, Normal/Fire, Normal/Poison, Normal/Steel, Fire/Water, Fire/Electric, Fire/Grass, Fire/Ice, Fire/Ground, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Rock, Fire/Ghost, Fire/Fairy, Water/Poison, Water/Steel, Electric/Poison, Electric/Steel, Grass/Poison, Grass/Steel, Ice/Poison, Ice/Steel, Poison/Ground, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Rock, Poison/Ghost, Poison/Fairy, Ground/Steel, Flying/Steel, Psychic/Steel, Bug/Steel, Rock/Steel, Ghost/Steel, Steel/Fairy]"
38,Flying,Resistant (0.5),39,"[Electric, Rock, Steel, Normal/Electric, Normal/Rock, Normal/Steel, Fire/Electric, Fire/Rock, Fire/Steel, Water/Electric, Water/Rock, Water/Steel, Electric/Ice, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Psychic, Electric/Ghost, Electric/Dragon, Electric/Dark, Electric/Fairy, Ice/Rock, Ice/Steel, Poison/Rock, Poison/Steel, Ground/Rock, Ground/Steel, Flying/Rock, Flying/Steel, Psychic/Rock, Psychic/Steel, Rock/Ghost, Rock/Dragon, Rock/Dark, Rock/Fairy, Ghost/Steel, Dragon/Steel, Dark/Steel, Steel/Fairy]"
90,Water,Resistant (0.5),39,"[Water, Grass, Dragon, Normal/Water, Normal/Grass, Normal/Dragon, Water/Electric, Water/Ice, Water/Fighting, Water/Poison, Water/Flying, Water/Psychic, Water/Bug, Water/Ghost, Water/Dark, Water/Steel, Water/Fairy, Electric/Grass, Electric/Dragon, Grass/Ice, Grass/Fighting, Grass/Poison, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Ghost, Grass/Dark, Grass/Steel, Grass/Fairy, Ice/Dragon, Fighting/Dragon, Poison/Dragon, Flying/Dragon, Psychic/Dragon, Bug/Dragon, Ghost/Dragon, Dragon/Dark, Dragon/Steel, Dragon/Fairy]"
80,Rock,Resistant (0.5),36,"[Fighting, Ground, Steel, Normal/Fighting, Normal/Ground, Normal/Steel, Water/Fighting, Water/Ground, Water/Steel, Electric/Fighting, Electric/Ground, Electric/Steel, Grass/Fighting, Grass/Ground, Grass/Steel, Fighting/Poison, Fighting/Psychic, Fighting/Rock, Fighting/Ghost, Fighting/Dragon, Fighting/Dark, Fighting/Fairy, Poison/Ground, Poison/Steel, Ground/Psychic, Ground/Rock, Ground/Ghost, Ground/Dragon, Ground/Dark, Ground/Fairy, Psychic/Steel, Rock/Steel, Ghost/Steel, Dragon/Steel, Dark/Steel, Steel/Fairy]"
65,Normal,Resistant (0.5),32,"[Rock, Steel, Normal/Rock, Normal/Steel, Fire/Rock, Fire/Steel, Water/Rock, Water/Steel, Electric/Rock, Electric/Steel, Grass/Rock, Grass/Steel, Ice/Rock, Ice/Steel, Fighting/Rock, Fighting/Steel, Poison/Rock, Poison/Steel, Ground/Rock, Ground/Steel, Flying/Rock, Flying/Steel, Psychic/Rock, Psychic/Steel, Bug/Rock, Bug/Steel, Rock/Dragon, Rock/Dark, Rock/Fairy, Dragon/Steel, Dark/Steel, Steel/Fairy]"
75,Psychic,Resistant (0.5),28,"[Psychic, Steel, Normal/Psychic, Normal/Steel, Fire/Psychic, Fire/Steel, Water/Psychic, Water/Steel, Electric/Psychic, Electric/Steel, Grass/Psychic, Grass/Steel, Ice/Psychic, Ice/Steel, Ground/Psychic, Ground/Steel, Flying/Psychic, Flying/Steel, Psychic/Bug, Psychic/Rock, Psychic/Ghost, Psychic/Dragon, Psychic/Fairy, Bug/Steel, Rock/Steel, Ghost/Steel, Dragon/Steel, Steel/Fairy]"
54,Ground,Resistant (0.5),22,"[Grass, Bug, Normal/Grass, Normal/Bug, Water/Grass, Water/Bug, Grass/Ice, Grass/Fighting, Grass/Ground, Grass/Psychic, Grass/Ghost, Grass/Dragon, Grass/Dark, Grass/Fairy, Ice/Bug, Fighting/Bug, Ground/Bug, Psychic/Bug, Bug/Ghost, Bug/Dragon, Bug/Dark, Bug/Fairy]"
12,Dragon,Resistant (0.5),16,"[Steel, Normal/Steel, Fire/Steel, Water/Steel, Electric/Steel, Grass/Steel, Ice/Steel, Fighting/Steel, Poison/Steel, Ground/Steel, Flying/Steel, Psychic/Steel, Bug/Steel, Rock/Steel, Ghost/Steel, Dark/Steel]"
43,Ghost,Resistant (0.5),15,"[Dark, Fire/Dark, Water/Dark, Electric/Dark, Grass/Dark, Ice/Dark, Fighting/Dark, Poison/Dark, Ground/Dark, Flying/Dark, Bug/Dark, Rock/Dark, Dragon/Dark, Dark/Steel, Dark/Fairy]"

In [515]:
attacking_types_category (table_categories_attacking, 'Neutral', ascending=False)

,Attack Type,Weakness Category,Count,Defensive Type
10,Dragon,Neutral,121,"[Normal, Fire, Water, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Psychic, Bug, Rock, Ghost, Dark, Normal/Fire, Normal/Water, Normal/Electric, Normal/Grass, Normal/Ice, Normal/Fighting, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Rock, Normal/Ghost, Normal/Dark, Fire/Water, Fire/Electric, Fire/Grass, Fire/Ice, Fire/Fighting, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Rock, Fire/Ghost, Fire/Dark, Water/Electric, Water/Grass, Water/Ice, Water/Fighting, Water/Poison, Water/Ground, Water/Flying, Water/Psychic, Water/Bug, Water/Rock, Water/Ghost, Water/Dark, Electric/Grass, Electric/Ice, Electric/Fighting, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Rock, Electric/Ghost, Electric/Dark, Grass/Ice, Grass/Fighting, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Rock, Grass/Ghost, Grass/Dark, Ice/Fighting, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Rock, Ice/Ghost, Ice/Dark, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Rock, Fighting/Ghost, Fighting/Dark, Poison/Ground, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Rock, Poison/Ghost, Poison/Dark, Ground/Flying, ...]"
62,Normal,Neutral,120,"[Normal, Fire, Water, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Psychic, Bug, Dragon, Dark, Fairy, Normal/Fire, Normal/Water, Normal/Electric, Normal/Grass, Normal/Ice, Normal/Fighting, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Dragon, Normal/Dark, Normal/Fairy, Fire/Water, Fire/Electric, Fire/Grass, Fire/Ice, Fire/Fighting, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Dragon, Fire/Dark, Fire/Fairy, Water/Electric, Water/Grass, Water/Ice, Water/Fighting, Water/Poison, Water/Ground, Water/Flying, Water/Psychic, Water/Bug, Water/Dragon, Water/Dark, Water/Fairy, Electric/Grass, Electric/Ice, Electric/Fighting, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Dragon, Electric/Dark, Electric/Fairy, Grass/Ice, Grass/Fighting, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Dragon, Grass/Dark, Grass/Fairy, Ice/Fighting, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Dragon, Ice/Dark, Ice/Fairy, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Dragon, Fighting/Dark, Fighting/Fairy, Poison/Ground, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Dragon, Poison/Dark, Poison/Fairy, Ground/Flying, ...]"
41,Ghost,Neutral,107,"[Fire, Water, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Bug, Rock, Dragon, Steel, Fairy, Fire/Water, Fire/Electric, Fire/Grass, Fire/Ice, Fire/Fighting, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Bug, Fire/Rock, Fire/Dragon, Fire/Steel, Fire/Fairy, Water/Electric, Water/Grass, Water/Ice, Water/Fighting, Water/Poison, Water/Ground, Water/Flying, Water/Bug, Water/Rock, Water/Dragon, Water/Steel, Water/Fairy, Electric/Grass, Electric/Ice, Electric/Fighting, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Bug, Electric/Rock, Electric/Dragon, Electric/Steel, Electric/Fairy, Grass/Ice, Grass/Fighting, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Bug, Grass/Rock, Grass/Dragon, Grass/Steel, Grass/Fairy, Ice/Fighting, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Bug, Ice/Rock, Ice/Dragon, Ice/Steel, Ice/Fairy, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Bug, Fighting/Rock, Fighting/Dragon, Fighting/Steel, Fighting/Fairy, Poison/Ground, Poison/Flying, Poison/Bug, Poison/Rock, Poison/Dragon, Poison/Steel, Poison/Fairy, Ground/Flying, Ground/Bug, Ground/Rock, Ground/Dragon, Ground/Steel, Ground/Fairy, Flying/Bug, Flying/Rock, Flying/Dragon, Flying/Steel, Flying/Fairy, Psychic/Dark, Bug/Rock, Bug/Dragon, Bug/Steel, Bug/Fairy, ...]"
5,Dark,Neutral,97,"[Normal, Fire, Water, Electric, Grass, Ice, Poison, Ground, Flying, Bug, Rock, Dragon, Steel, Normal/Fire, Normal/Water, Normal/Electric, Normal/Grass, Normal/Ice, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Bug, Normal/Rock, Normal/Dragon, Normal/Steel, Fire/Water, Fire/Electric, Fire/Grass, Fire/Ice, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Bug, Fire/Rock, Fire/Dragon, Fire/Steel, Water/Electric, Water/Grass, Water/Ice, Water/Poison, Water/Ground, Water/Flying, Water/Bug, Water/Rock, Water/Dragon, Water/Steel, Electric/Grass, Electric/Ice, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Bug, Electric/Rock, Electric/Dragon, Electric/Steel, Grass/Ice, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Bug, Grass/Rock, Grass/Dragon, Grass/Steel, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Bug, Ice/Rock, Ice/Dragon, Ice/Steel, Fighting/Psychic, Fighting/Ghost, Poison/Ground, Poison/Flying, Poison/Bug, Poison/Rock, Poison/Dragon, Poison/Steel, Ground/Flying, Ground/Bug, Ground/Rock, Ground/Dragon, Ground/Steel, Flying/Bug, Flying/Rock, Flying/Dragon, Flying/Steel, Psychic/Dark, Psychic/Fairy, Bug/Rock, Bug/Dragon, Bug/Steel, Rock/Dragon, Rock/Steel, Ghost/Dark, Ghost/Fairy, Dragon/Steel]"
72,Psychic,Neutral,95,"[Normal, Fire, Water, Electric, Grass, Ice, Ground, Flying, Bug, Rock, Ghost, Dragon, Fairy, Normal/Fire, Normal/Water, Normal/Electric, Normal/Grass, Normal/Ice, Normal/Ground, Normal/Flying, Normal/Bug, Normal/Rock, Normal/Ghost, Normal/Dragon, Normal/Fairy, Fire/Water, Fire/Electric, Fire/Grass, Fire/Ice, Fire/Ground, Fire/Flying, Fire/Bug, Fire/Rock, Fire/Ghost, Fire/Dragon, Fire/Fairy, Water/Electric, Water/Grass, Water/Ice, Water/Ground, Water/Flying, Water/Bug, Water/Rock, Water/Ghost, Water/Dragon, Water/Fairy, Electric/Grass, Electric/Ice, Electric/Ground, Electric/Flying, Electric/Bug, Electric/Rock, Electric/Ghost, Electric/Dragon, Electric/Fairy, Grass/Ice, Grass/Ground, Grass/Flying, Grass/Bug, Grass/Rock, Grass/Ghost, Grass/Dragon, Grass/Fairy, Ice/Ground, Ice/Flying, Ice/Bug, Ice/Rock, Ice/Ghost, Ice/Dragon, Ice/Fairy, Fighting/Psychic, Fighting/Steel, Poison/Psychic, Poison/Steel, Ground/Flying, Ground/Bug, Ground/Rock, Ground/Ghost, Ground/Dragon, Ground/Fairy, Flying/Bug, Flying/Rock, Flying/Ghost, Flying/Dragon, Flying/Fairy, Bug/Rock, Bug/Ghost, Bug/Dragon, Bug/Fairy, Rock/Ghost, Rock/Dragon, Rock/Fairy, Ghost/Dragon, Ghost/Fairy, Dragon/Fairy]"
88,Water,Neutral,87,"[Normal, Electric, Ice, Fighting, Poison, Flying, Psychic, Bug, Ghost, Dark, Steel, Fairy, Normal/Electric, Normal/Ice, Normal/Fighting, Normal/Poison, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Ghost, Normal/Dark, Normal/Steel, Normal/Fairy, Fire/Water, Fire/Grass, Fire/Dragon, Water/Ground, Water/Rock, Electric/Ice, Electric/Fighting, Electric/Poison, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Ghost, Electric/Dark, Electric/Steel, Electric/Fairy, Grass/Ground, Grass/Rock, Ice/Fighting, Ice/Poison, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Ghost, Ice/Dark, Ice/Steel, Ice/Fairy, Fighting/Poison, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Ghost, Fighting/Dark, Fighting/Steel, Fighting/Fairy, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Ghost, Poison/Dark, Poison/Steel, Poison/Fairy, Ground/Dragon, Flying/Psychic, Flying/Bug, Flying/Ghost, Flying/Dark, Flying/Steel, Flying/Fairy, Psychic/Bug, Psychic/Ghost, Psychic/Dark, Psychic/Steel, Psychic/Fairy, Bug/Ghost, Bug/Dark, Bug/Steel, Bug/Fairy, Rock/Dragon, Ghost/Dark, Ghost/Steel, Ghost/Fairy, Dark/Steel, Dark/Fairy, Steel/Fairy]"
20,Fairy,Neutral,87,"[Normal, Water, Electric, Grass, Ice, Ground, Flying, Psychic, Bug, Rock, Ghost, Fairy, Normal/Water, Normal/Electric, Normal/Grass, Normal/Ice, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Rock, Normal/Ghost, Normal/Fairy, Fire/Fighting, Fire/Dragon, Fire/Dark, Water/Electric, Water/Grass, Water/Ice, Water/Ground, Water/Flying, Water/Psychic, Water/Bug, Water/Rock, Water/Ghost, Water/Fairy, Electric/Grass, Electric/Ice, Electric/Ground, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Rock, Electric/Ghost, Electric/Fairy, Grass/Ice, Grass/Ground, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Rock, Grass/Ghost, Grass/Fairy, Ice/Ground, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Rock, Ice/Ghost, Ice/Fairy, Fighting/Poison, Fighting/Steel, Poison/Dragon, Poison/Dark, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Rock, Ground/Ghost, Ground/Fairy, Flying/Psychic, Flying/Bug, Flying/Rock, Flying/Ghost, Flying/Fairy, Psychic/Bug, Psychic/Rock, Psychic/Ghost, Psychic/Fairy, Bug/Rock, Bug/Ghost, Bug/Fairy, Rock/Ghost, Rock/Fairy, Ghost/Fairy, Dragon/Steel, Dark/Steel]"
36,Flying,Neutral,87,"[Normal, Fire, Water, Ice, Poison, Ground, Flying, Psychic, Ghost, Dragon, Dark, Fairy, Normal/Fire, Normal/Water, Normal/Ice, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Ghost, Normal/Dragon, Normal/Dark, Normal/Fairy, Fire/Water, Fire/Ice, Fire/Poison, Fire/Ground, Fire/Flying, Fire/Psychic, Fire/Ghost, Fire/Dragon, Fire/Dark, Fire/Fairy, Water/Ice, Water/Poison, Water/Ground, Water/Flying, Water/Psychic, Water/Ghost, Water/Dragon, Water/Dark, Water/Fairy, Electric/Grass, Electric/Fighting, Electric/Bug, Grass/Rock, Grass/Steel, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Psychic, Ice/Ghost, Ice/Dragon, Ice/Dark, Ice/Fairy, Fighting/Rock, Fighting/Steel, Poison/Ground, Poison/Flying, Poison/Psychic, Poison/Ghost, Poison/Dragon, Poison/Dark, Poison/Fairy, Ground/Flying, Ground/Psychic, Ground/Ghost, Ground/Dragon, Ground/Dark, Ground/Fairy, Flying/Psychic, Flying/Ghost, Flying/Dragon, Flying/Dark, Flying/Fairy, Psychic/Ghost, Psychic/Dragon, Psychic/Dark, Psychic/Fairy, Bug/Rock, Bug/Steel, Ghost/Dragon, Ghost/Dark, Ghost/Fairy, Dragon/Dark, Dragon/Fairy, Dark/Fairy]"
14,Electric,Neutral,84,"[Normal, Fire, Ice, Fighting, Poison, Psychic, Bug, Rock, Ghost, Dark, Steel, Fairy, Normal/Fire, Normal/Ice, Normal/Fighting, Normal/Poison, Normal/Psychic, Normal/Bug, Normal/Rock, Normal/Ghost, Normal/Dark, Normal/Steel, Normal/Fairy, Fire/Ice, Fire/Fighting, Fire/Poison, Fire/Psychic, Fire/Bug, Fire/Rock, Fire/Ghost, Fire/Dark, Fire/Steel, Fire/Fairy, Water/Electric, Water/Grass, Water/Dragon, Electric/Flying, Grass/Flying, Ice/Fighting, Ice/Poison, Ice/Psychic, Ice/Bug, Ice/Rock, Ice/Ghost, Ice/Dark, Ice/Steel, Ice/Fairy, Fighting/Poison, Fighting/Psychic, Fighting/Bug, Fighting/Rock, Fighting/Ghost, Fighting/Dark, Fighting/Steel, Fighting/Fairy, Poison/Psychic, Poison/Bug, Poison/Rock, Poison/Ghost, Poison/Dark, Poison/Steel, Poison/Fairy, Flying/Dragon, Psychic/Bug, Psychic/Rock, Psychic/Ghost, Psychic/Dark, Psychic/Steel, Psychic/Fairy, Bug/Rock, Bug/Ghost, Bug/Dark, Bug/Steel, Bug/Fairy, Rock/Ghost, Rock/Dark, Rock/Steel, Rock/Fairy, Ghost/Dark, Ghost/Steel, Ghost/Fairy, Dark/Steel, Dark/Fairy, Steel/Fairy]"
78,Rock,Neutral,78,"[Normal, Water, Electric, Grass, Poison, Psychic, Rock, Ghost, Dragon, Dark, Fairy, Normal/Water, Normal/Electric, Normal/Grass, Normal/Poison, Normal/Psychic, Normal/Rock, Normal/Ghost, Normal/Dragon, Normal/Dark, Normal/Fairy, Fire/Fighting, Fire/Ground, Fire/Steel, Water/Electric, Water/Grass, Water/Poison, Water/Psychic, Water/Rock, Water/Ghost, Water/Dragon, Water/Dark, Water/Fairy, Electric/Grass, Electric/Poison, Electric/Psychic, Electric/Rock, Electric/Ghost, Electric/Dragon, Electric/Dark, Electric/Fairy, Grass/Poison, Grass/Psychic, Grass/Rock, Grass/Ghost, Grass/Dragon, Grass/Dark, Grass/Fairy, Ice/Fighting, Ice/Ground, Ice/Steel, Fighting/Flying, Fighting/Bug, Poison/Psychic, Poison/Rock, Poison/Ghost, Poison/Dragon, Poison/Dark, Poison/Fairy, Ground/Flying, Ground/Bug, Flying/Steel, Psychic/Rock, Psychic/Ghost, Psychic/Dragon, Psychic/Dark, Psychic/Fairy, Bug/Steel, Rock/Ghost, Rock/Dragon, Rock/Dark, Rock/Fairy, Ghost/Dragon, Ghost/Dark, Ghost/Fairy, Dragon/Dark, Dragon/Fairy, Dark/Fairy]"
83,Steel,Neutral,78,"[Normal, Grass, Fighting, Poison, Ground, Flying, Psychic, Bug, Ghost, Dragon, Dark, Normal/Grass, Normal/Fighting, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Ghost, Normal/Dragon, Normal/Dark, Fire/Ice, Fire/Rock, Fire/Fairy, Water/Ice, Water/Rock, Water/Fairy, Electric/Ice, Electric/Rock, Electric/Fairy, Grass/Fighting, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Ghost, Grass/Dragon, Grass/Dark, Ice/Steel, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Ghost, Fighting/Dragon, Fighting/Dark, Poison/Ground, Poison/Flying, Poison/Psychic, Poison/Bug, Poison/Ghost, Poison/Dragon, Poison/Dark, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Ghost, Ground/Dragon, Ground/Dark, Flying/Psychic, Flying/Bug, Flying/Ghost, Flying/Dragon, Flying/Dark, Psychic/Bug, Psychic/Ghost, Psychic/Dragon, Psychic/Dark, Bug/Ghost, Bug/Dragon, Bug/Dark, Rock/Steel, Ghost/Dragon, Ghost/Dark, Dragon/Dark, Steel/Fairy]"
66,Poison,Neutral,74,"[Normal, Fire, Water, Electric, Ice, Fighting, Flying, Psychic, Bug, Dragon, Dark, Normal/Fire, Normal/Water, Normal/Electric, Normal/Ice, Normal/Fighting, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Dragon, Normal/Dark, Fire/Water, Fire/Electric, Fire/Ice, Fire/Fighting, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Dragon, Fire/Dark, Water/Electric, Water/Ice, Water/Fighting, Water/Flying, Water/Psychic, Water/Bug, Water/Dragon, Water/Dark, Electric/Ice, Electric/Fighting, Electric/Flying, Electric/Psychic, Electric/Bug, Electric/Dragon, Electric/Dark, Grass/Poison, Grass/Ground, Grass/Rock, Grass/Ghost, Ice/Fighting, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Dragon, Ice/Dark, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Dragon, Fighting/Dark, Poison/Fairy, Ground/Fairy, Flying/Psychic, Flying/Bug, Flying/Dragon, Flying/Dark, Psychic/Bug, Psychic/Dragon, Psychic/Dark, Bug/Dragon, Bug/Dark, Rock/Fairy, Ghost/Fairy, Dragon/Dark]"
31,Fire,Neutral,71,"[Normal, Electric, Fighting, Poison, Ground, Flying, Psychic, Ghost, Dark, Fairy, Normal/Electric, Normal/Fighting, Normal/Poison, Normal/Ground, Normal/Flying, Normal/Psychic, Normal/Ghost, Normal/Dark, Normal/Fairy, Fire/Grass, Fire/Ice, Fire/Bug, Fire/Steel, Water/Grass, Water/Ice, Water/Bug, Water/Steel, Electric/Fighting, Electric/Poison, Electric/Ground, Electric/Flying, Electric/Psychic, Electric/Ghost, Electric/Dark, Electric/Fairy, Grass/Rock, Grass/Dragon, Ice/Rock, Ice/Dragon, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Psychic, Fighting/Ghost, Fighting/Dark, Fighting/Fairy, Poison/Ground, Poison/Flying, Poison/Psychic, Poison/Ghost, Poison/Dark, Poison/Fairy, Ground/Flying, Ground/Psychic, Ground/Ghost, Ground/Dark, Ground/Fairy, Flying/Psychic, Flying/Ghost, Flying/Dark, Flying/Fairy, Psychic/Ghost, Psychic/Dark, Psychic/Fairy, Bug/Rock, Bug/Dragon, Rock/Steel, Ghost/Dark, Ghost/Fairy, Dragon/Steel, Dark/Fairy]"
57,Ice,Neutral,71,"[Normal, Electric, Fighting, Poison, Psychic, Bug, Rock, Ghost, Dark, Fairy, Normal/Electric, Normal/Fighting, Normal/Poison, Normal/Psychic, Normal/Bug, Normal/Rock, Normal/Ghost, Normal/Dark, Normal/Fairy, Fire/Grass, Fire/Ground, Fire/Flying, Fire/Dragon, Water/Grass, Water/Ground, Water/Flying, Water/Dragon, Electric/Fighting, Electric/Poison, Electric/Psychic, Electric/Bug, Electric/Rock, Electric/Ghost, Electric/Dark, Electric/Fairy, Grass/Ice, Grass/Steel, Ice/Ground, Ice/Flying, Ice/Dragon, Fighting/Poison, Fighting/Psychic, Fighting/Bug, Fighting/Rock, Fighting/Ghost, Fighting/Dark, Fighting/Fairy, Poison/Psychic, Poison/Bug, Poison/Rock, Poison/Ghost, Poison/Dark, Poison/Fairy, Ground/Steel, Flying/Steel, Psychic/Bug, Psychic/Rock, Psychic/Ghost, Psychic/Dark, Psychic/Fairy, Bug/Rock, Bug/Ghost, Bug/Dark, Bug/Fairy, Rock/Ghost, Rock/Dark, Rock/Fairy, Ghost/Dark, Ghost/Fairy, Dragon/Steel, Dark/Fairy]"
51,Ground,Neutral,65,"[Normal, Water, Ice, Fighting, Ground, Psychic, Ghost, Dragon, Dark, Fairy, Normal/Water, Normal/Ice, Normal/Fighting, Normal/Ground, Normal/Psychic, Normal/Ghost, Normal/Dragon, Normal/Dark, Normal/Fairy, Fire/Grass, Fire/Bug, Water/Ice, Water/Fighting, Water/Ground, Water/Psychic, Water/Ghost, Water/Dragon, Water/Dark, Water/Fairy, Electric/Grass, Electric/Bug, Grass/Poison, Grass/Rock, Grass/Steel, Ice/Fighting, Ice/Ground, Ice/Psychic, Ice/Ghost, Ice/Dragon, Ice/Dark, Ice/Fairy, Fighting/Ground, Fighting/Psychic, Fighting/Ghost, Fighting/Dragon, Fighting/Dark, Fighting/Fairy, Poison/Bug, Ground/Psychic, Ground/Ghost, Ground/Dragon, Ground/Dark, Ground/Fairy, Psychic/Ghost, Psychic/Dragon, Psychic/Dark, Psychic/Fairy, Bug/Rock, Bug/Steel, Ghost/Dragon, Ghost/Dark, Ghost/Fairy, Dragon/Dark, Dragon/Fairy, Dark/Fairy]"
0,Bug,Neutral,57,"[Normal, Water, Electric, Ice, Ground, Bug, Rock, Dragon, Normal/Water, Normal/Electric, Normal/Ice, Normal/Ground, Normal/Bug, Normal/Rock, Normal/Dragon, Fire/Grass, Fire/Psychic, Fire/Dark, Water/Electric, Water/Ice, Water/Ground, Water/Bug, Water/Rock, Water/Dragon, Electric/Ice, Electric/Ground, Electric/Bug, Electric/Rock, Electric/Dragon, Grass/Fighting, Grass/Poison, Grass/Flying, Grass/Ghost, Grass/Steel, Grass/Fairy, Ice/Ground, Ice/Bug, Ice/Rock, Ice/Dragon, Fighting/Psychic, Fighting/Dark, Poison/Psychic, Poison/Dark, Ground/Bug, Ground/Rock, Ground/Dragon, Flying/Psychic, Flying/Dark, Psychic/Ghost, Psychic/Steel, Psychic/Fairy, Bug/Rock, Bug/Dragon, Rock/Dragon, Ghost/Dark, Dark/Steel, Dark/Fairy]"
46,Grass,Neutral,57,"[Normal, Electric, Ice, Fighting, Psychic, Ghost, Dark, Fairy, Normal/Electric, Normal/Ice, Normal/Fighting, Normal/Psychic, Normal/Ghost, Normal/Dark, Normal/Fairy, Fire/Water, Fire/Ground, Fire/Rock, Water/Grass, Water/Poison, Water/Flying, Water/Bug, Water/Dragon, Water/Steel, Electric/Ice, Electric/Fighting, Electric/Psychic, Electric/Ghost, Electric/Dark, Electric/Fairy, Grass/Ground, Grass/Rock, Ice/Fighting, Ice/Psychic, Ice/Ghost, Ice/Dark, Ice/Fairy, Fighting/Psychic, Fighting/Ghost, Fighting/Dark, Fighting/Fairy, Poison/Ground, Poison/Rock, Ground/Flying, Ground/Bug, Ground/Dragon, Ground/Steel, Flying/Rock, Psychic/Ghost, Psychic/Dark, Psychic/Fairy, Bug/Rock, Rock/Dragon, Rock/Steel, Ghost/Dark, Ghost/Fairy, Dark/Fairy]"
25,Fighting,Neutral,53,"[Fire, Water, Electric, Grass, Fighting, Ground, Dragon, Normal/Poison, Normal/Flying, Normal/Psychic, Normal/Bug, Normal/Fairy, Fire/Water, Fire/Electric, Fire/Grass, Fire/Fighting, Fire/Ground, Fire/Dragon, Water/Electric, Water/Grass, Water/Fighting, Water/Ground, Water/Dragon, Electric/Grass, Electric/Fighting, Electric/Ground, Electric/Dragon, Grass/Fighting, Grass/Ground, Grass/Dragon, Ice/Poison, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Fairy, Fighting/Ground, Fighting/Dragon, Poison/Rock, Poison/Dark, Poison/Steel, Ground/Dragon, Flying/Rock, Flying/Dark, Flying/Steel, Psychic/Rock, Psychic/Dark, Psychic/Steel, Bug/Rock, Bug/Dark, Bug/Steel, Rock/Fairy, Dark/Fairy, Steel/Fairy]"

In [516]:
attacking_types_category (table_categories_attacking, 'Super Effective (2)', ascending=False)

,Attack Type,Weakness Category,Count,Defensive Type
55,Ground,Super Effective (2),55,"[Fire, Electric, Poison, Rock, Steel, Normal/Fire, Normal/Electric, Normal/Poison, Normal/Rock, Normal/Steel, Fire/Water, Fire/Ice, Fire/Fighting, Fire/Ground, Fire/Psychic, Fire/Ghost, Fire/Dragon, Fire/Dark, Fire/Fairy, Water/Electric, Water/Poison, Water/Rock, Water/Steel, Electric/Ice, Electric/Fighting, Electric/Ground, Electric/Psychic, Electric/Ghost, Electric/Dragon, Electric/Dark, Electric/Fairy, Ice/Poison, Ice/Rock, Ice/Steel, Fighting/Poison, Fighting/Rock, Fighting/Steel, Poison/Ground, Poison/Psychic, Poison/Ghost, Poison/Dragon, Poison/Dark, Poison/Fairy, Ground/Rock, Ground/Steel, Psychic/Rock, Psychic/Steel, Rock/Ghost, Rock/Dragon, Rock/Dark, Rock/Fairy, Ghost/Steel, Dragon/Steel, Dark/Steel, Steel/Fairy]"
81,Rock,Super Effective (2),48,"[Fire, Ice, Flying, Bug, Normal/Fire, Normal/Ice, Normal/Flying, Normal/Bug, Fire/Water, Fire/Electric, Fire/Grass, Fire/Poison, Fire/Psychic, Fire/Rock, Fire/Ghost, Fire/Dragon, Fire/Dark, Fire/Fairy, Water/Ice, Water/Flying, Water/Bug, Electric/Ice, Electric/Flying, Electric/Bug, Grass/Ice, Grass/Flying, Grass/Bug, Ice/Poison, Ice/Psychic, Ice/Rock, Ice/Ghost, Ice/Dragon, Ice/Dark, Ice/Fairy, Poison/Flying, Poison/Bug, Flying/Psychic, Flying/Rock, Flying/Ghost, Flying/Dragon, Flying/Dark, Flying/Fairy, Psychic/Bug, Bug/Rock, Bug/Ghost, Bug/Dragon, Bug/Dark, Bug/Fairy]"
34,Fire,Super Effective (2),44,"[Grass, Ice, Bug, Steel, Normal/Grass, Normal/Ice, Normal/Bug, Normal/Steel, Electric/Grass, Electric/Ice, Electric/Bug, Electric/Steel, Grass/Fighting, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Psychic, Grass/Ghost, Grass/Dark, Grass/Fairy, Ice/Fighting, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Psychic, Ice/Ghost, Ice/Dark, Ice/Fairy, Fighting/Bug, Fighting/Steel, Poison/Bug, Poison/Steel, Ground/Bug, Ground/Steel, Flying/Bug, Flying/Steel, Psychic/Bug, Psychic/Steel, Bug/Ghost, Bug/Dark, Bug/Fairy, Ghost/Steel, Dark/Steel, Steel/Fairy]"
60,Ice,Super Effective (2),44,"[Grass, Ground, Flying, Dragon, Normal/Grass, Normal/Ground, Normal/Flying, Normal/Dragon, Electric/Grass, Electric/Ground, Electric/Flying, Electric/Dragon, Grass/Fighting, Grass/Poison, Grass/Psychic, Grass/Bug, Grass/Rock, Grass/Ghost, Grass/Dark, Grass/Fairy, Fighting/Ground, Fighting/Flying, Fighting/Dragon, Poison/Ground, Poison/Flying, Poison/Dragon, Ground/Psychic, Ground/Bug, Ground/Rock, Ground/Ghost, Ground/Dark, Ground/Fairy, Flying/Psychic, Flying/Bug, Flying/Rock, Flying/Ghost, Flying/Dark, Flying/Fairy, Psychic/Dragon, Bug/Dragon, Rock/Dragon, Ghost/Dragon, Dragon/Dark, Dragon/Fairy]"
29,Fighting,Super Effective (2),40,"[Normal, Ice, Rock, Dark, Steel, Normal/Fire, Normal/Water, Normal/Electric, Normal/Grass, Normal/Fighting, Normal/Ground, Normal/Dragon, Fire/Ice, Fire/Rock, Fire/Dark, Fire/Steel, Water/Ice, Water/Rock, Water/Dark, Water/Steel, Electric/Ice, Electric/Rock, Electric/Dark, Electric/Steel, Grass/Ice, Grass/Rock, Grass/Dark, Grass/Steel, Ice/Fighting, Ice/Ground, Ice/Dragon, Fighting/Rock, Fighting/Dark, Fighting/Steel, Ground/Rock, Ground/Dark, Ground/Steel, Rock/Dragon, Dragon/Dark, Dragon/Steel]"
91,Water,Super Effective (2),39,"[Fire, Ground, Rock, Normal/Fire, Normal/Ground, Normal/Rock, Fire/Electric, Fire/Ice, Fire/Fighting, Fire/Poison, Fire/Flying, Fire/Psychic, Fire/Bug, Fire/Ghost, Fire/Dark, Fire/Steel, Fire/Fairy, Electric/Ground, Electric/Rock, Ice/Ground, Ice/Rock, Fighting/Ground, Fighting/Rock, Poison/Ground, Poison/Rock, Ground/Flying, Ground/Psychic, Ground/Bug, Ground/Ghost, Ground/Dark, Ground/Steel, Ground/Fairy, Flying/Rock, Psychic/Rock, Bug/Rock, Rock/Ghost, Rock/Dark, Rock/Steel, Rock/Fairy]"
23,Fairy,Super Effective (2),39,"[Fighting, Dragon, Dark, Normal/Fighting, Normal/Dragon, Normal/Dark, Water/Fighting, Water/Dragon, Water/Dark, Electric/Fighting, Electric/Dragon, Electric/Dark, Grass/Fighting, Grass/Dragon, Grass/Dark, Ice/Fighting, Ice/Dragon, Ice/Dark, Fighting/Ground, Fighting/Flying, Fighting/Psychic, Fighting/Bug, Fighting/Rock, Fighting/Ghost, Fighting/Fairy, Ground/Dragon, Ground/Dark, Flying/Dragon, Flying/Dark, Psychic/Dragon, Psychic/Dark, Bug/Dragon, Bug/Dark, Rock/Dragon, Rock/Dark, Ghost/Dragon, Ghost/Dark, Dragon/Fairy, Dark/Fairy]"
39,Flying,Super Effective (2),39,"[Grass, Fighting, Bug, Normal/Grass, Normal/Fighting, Normal/Bug, Fire/Grass, Fire/Fighting, Fire/Bug, Water/Grass, Water/Fighting, Water/Bug, Grass/Ice, Grass/Poison, Grass/Ground, Grass/Flying, Grass/Psychic, Grass/Ghost, Grass/Dragon, Grass/Dark, Grass/Fairy, Ice/Fighting, Ice/Bug, Fighting/Poison, Fighting/Ground, Fighting/Flying, Fighting/Psychic, Fighting/Ghost, Fighting/Dragon, Fighting/Dark, Fighting/Fairy, Poison/Bug, Ground/Bug, Flying/Bug, Psychic/Bug, Bug/Ghost, Bug/Dragon, Bug/Dark, Bug/Fairy]"
86,Steel,Super Effective (2),36,"[Ice, Rock, Fairy, Normal/Ice, Normal/Rock, Normal/Fairy, Grass/Ice, Grass/Rock, Grass/Fairy, Ice/Fighting, Ice/Poison, Ice/Ground, Ice/Flying, Ice/Psychic, Ice/Bug, Ice/Ghost, Ice/Dragon, Ice/Dark, Fighting/Rock, Fighting/Fairy, Poison/Rock, Poison/Fairy, Ground/Rock, Ground/Fairy, Flying/Rock, Flying/Fairy, Psychic/Rock, Psychic/Fairy, Bug/Rock, Bug/Fairy, Rock/Ghost, Rock/Dragon, Rock/Dark, Ghost/Fairy, Dragon/Fairy, Dark/Fairy]"
44,Ghost,Super Effective (2),30,"[Psychic, Ghost, Fire/Psychic, Fire/Ghost, Water/Psychic, Water/Ghost, Electric/Psychic, Electric/Ghost, Grass/Psychic, Grass/Ghost, Ice/Psychic, Ice/Ghost, Fighting/Psychic, Fighting/Ghost, Poison/Psychic, Poison/Ghost, Ground/Psychic, Ground/Ghost, Flying/Psychic, Flying/Ghost, Psychic/Bug, Psychic/Rock, Psychic/Dragon, Psychic/Steel, Psychic/Fairy, Bug/Ghost, Rock/Ghost, Ghost/Dragon, Ghost/Steel, Ghost/Fairy]"
8,Dark,Super Effective (2),28,"[Psychic, Ghost, Normal/Psychic, Normal/Ghost, Fire/Psychic, Fire/Ghost, Water/Psychic, Water/Ghost, Electric/Psychic, Electric/Ghost, Grass/Psychic, Grass/Ghost, Ice/Psychic, Ice/Ghost, Poison/Psychic, Poison/Ghost, Ground/Psychic, Ground/Ghost, Flying/Psychic, Flying/Ghost, Psychic/Bug, Psychic/Rock, Psychic/Dragon, Psychic/Steel, Bug/Ghost, Rock/Ghost, Ghost/Dragon, Ghost/Steel]"
76,Psychic,Super Effective (2),28,"[Fighting, Poison, Normal/Fighting, Normal/Poison, Fire/Fighting, Fire/Poison, Water/Fighting, Water/Poison, Electric/Fighting, Electric/Poison, Grass/Fighting, Grass/Poison, Ice/Fighting, Ice/Poison, Fighting/Ground, Fighting/Flying, Fighting/Bug, Fighting/Rock, Fighting/Ghost, Fighting/Dragon, Fighting/Fairy, Poison/Ground, Poison/Flying, Poison/Bug, Poison/Rock, Poison/Ghost, Poison/Dragon, Poison/Fairy]"
49,Grass,Super Effective (2),27,"[Water, Ground, Rock, Normal/Water, Normal/Ground, Normal/Rock, Water/Electric, Water/Ice, Water/Fighting, Water/Psychic, Water/Ghost, Water/Dark, Water/Fairy, Electric/Ground, Electric/Rock, Ice/Ground, Ice/Rock, Fighting/Ground, Fighting/Rock, Ground/Psychic, Ground/Ghost, Ground/Dark, Ground/Fairy, Psychic/Rock, Rock/Ghost, Rock/Dark, Rock/Fairy]"
3,Bug,Super Effective (2),27,"[Grass, Psychic, Dark, Normal/Grass, Normal/Psychic, Normal/Dark, Water/Grass, Water/Psychic, Water/Dark, Electric/Grass, Electric/Psychic, Electric/Dark, Grass/Ice, Grass/Ground, Grass/Bug, Grass/Rock, Grass/Dragon, Ice/Psychic, Ice/Dark, Ground/Psychic, Ground/Dark, Psychic/Bug, Psychic/Rock, Psychic/Dragon, Bug/Dark, Rock/Dark, Dragon/Dark]"
18,Electric,Super Effective (2),26,"[Water, Flying, Normal/Water, Normal/Flying, Fire/Water, Fire/Flying, Water/Ice, Water/Fighting, Water/Poison, Water/Psychic, Water/Bug, Water/Rock, Water/Ghost, Water/Dark, Water/Steel, Water/Fairy, Ice/Flying, Fighting/Flying, Poison/Flying, Flying/Psychic, Flying/Bug, Flying/Rock, Flying/Ghost, Flying/Dark, Flying/Steel, Flying/Fairy]"
70,Poison,Super Effective (2),24,"[Grass, Fairy, Normal/Grass, Normal/Fairy, Fire/Grass, Fire/Fairy, Water/Grass, Water/Fairy, Electric/Grass, Electric/Fairy, Grass/Ice, Grass/Fighting, Grass/Flying, Grass/Psychic, Grass/Bug, Grass/Dragon, Grass/Dark, Ice/Fairy, Fighting/Fairy, Flying/Fairy, Psychic/Fairy, Bug/Fairy, Dragon/Fairy, Dark/Fairy]"
13,Dragon,Super Effective (2),16,"[Dragon, Normal/Dragon, Fire/Dragon, Water/Dragon, Electric/Dragon, Grass/Dragon, Ice/Dragon, Fighting/Dragon, Poison/Dragon, Ground/Dragon, Flying/Dragon, Psychic/Dragon, Bug/Dragon, Rock/Dragon, Ghost/Dragon, Dragon/Dark]"

In [481]:
attacking_types_category (table_categories_attacking, 'Super Effective (4)', ascending=False)

,Attack Type,Weakness Category,Count,Defensive Type
30,Fighting,Super Effective (4),10,"[Normal/Ice, Normal/Rock, Normal/Dark, Normal/..."
56,Ground,Super Effective (4),10,"[Fire/Electric, Fire/Poison, Fire/Rock, Fire/S..."
35,Fire,Super Effective (4),6,"[Grass/Ice, Grass/Bug, Grass/Steel, Ice/Bug, I..."
61,Ice,Super Effective (4),6,"[Grass/Ground, Grass/Flying, Grass/Dragon, Gro..."
82,Rock,Super Effective (4),6,"[Fire/Ice, Fire/Flying, Fire/Bug, Ice/Flying, ..."
4,Bug,Super Effective (4),3,"[Grass/Psychic, Grass/Dark, Psychic/Dark]"
24,Fairy,Super Effective (4),3,"[Fighting/Dragon, Fighting/Dark, Dragon/Dark]"
40,Flying,Super Effective (4),3,"[Grass/Fighting, Grass/Bug, Fighting/Bug]"
50,Grass,Super Effective (4),3,"[Water/Ground, Water/Rock, Ground/Rock]"
87,Steel,Super Effective (4),3,"[Ice/Rock, Ice/Fairy, Rock/Fairy]"
92,Water,Super Effective (4),3,"[Fire/Ground, Fire/Rock, Ground/Rock]"
9,Dark,Super Effective (4),1,[Psychic/Ghost]
19,Electric,Super Effective (4),1,[Water/Flying]
45,Ghost,Super Effective (4),1,[Psychic/Ghost]
71,Poison,Super Effective (4),1,[Grass/Fairy]
77,Psychic,Super Effective (4),1,[Fighting/Poison]

In [507]:
def bar_plot_weakness_category_attacking (df, attacking_type):
    
    order_list = ['Neutral', 'No Effect', 'Resistant (0.25)', 'Resistant (0.5)', 'Super Effective (2)', 'Super Effective (4)']

    custom_palette = ['#1f77b4', '#d3d3d3', '#2ca02c', '#006400', '#ff6347', '#b22222']

    fig = px.bar(
        df[df['Attack Type']==attacking_type],
        x='Weakness Category',
        y='Count',
        color='Weakness Category',
        title=f"Attacking Effects for {attacking_type} Type",
        category_orders={'Weakness Category': order_list},
        color_discrete_map={'Neutral': custom_palette[0], 'No Effect': custom_palette[1],
                           'Resistant (0.25)': custom_palette[2], 'Resistant (0.5)': custom_palette[3],
                           'Super Effective (2)': custom_palette[4], 'Super Effective (4)': custom_palette[5]}
    )

    fig.update_layout(
        title={'x': 0.5, 'xanchor': 'center', 'y': 0.95},  
        font=dict(family="Arial", size=14),  
        yaxis=dict(tickformat=".0f", showgrid=True, gridcolor='gray', gridwidth=0.2, title=None), 
        xaxis=dict(title=None),
        plot_bgcolor='white',  
        height=600,  
        width=900,  
    )

    fig.show()
    
    return df[df['Attack Type']==attacking_type]

In [511]:
bar_plot_weakness_category_attacking (table_categories_attacking, 'Ground')

,Attack Type,Weakness Category,Count,Defensive Type
51,Ground,Neutral,65,"[Normal, Water, Ice, Fighting, Ground, Psychic, Ghost, Dragon, Dark, Fairy, Normal/Water, Normal/Ice, Normal/Fighting, Normal/Ground, Normal/Psychic, Normal/Ghost, Normal/Dragon, Normal/Dark, Normal/Fairy, Fire/Grass, Fire/Bug, Water/Ice, Water/Fighting, Water/Ground, Water/Psychic, Water/Ghost, Water/Dragon, Water/Dark, Water/Fairy, Electric/Grass, Electric/Bug, Grass/Poison, Grass/Rock, Grass/Steel, Ice/Fighting, Ice/Ground, Ice/Psychic, Ice/Ghost, Ice/Dragon, Ice/Dark, Ice/Fairy, Fighting/Ground, Fighting/Psychic, Fighting/Ghost, Fighting/Dragon, Fighting/Dark, Fighting/Fairy, Poison/Bug, Ground/Psychic, Ground/Ghost, Ground/Dragon, Ground/Dark, Ground/Fairy, Psychic/Ghost, Psychic/Dragon, Psychic/Dark, Psychic/Fairy, Bug/Rock, Bug/Steel, Ghost/Dragon, Ghost/Dark, Ghost/Fairy, Dragon/Dark, Dragon/Fairy, Dark/Fairy]"
52,Ground,No Effect,18,"[Flying, Normal/Flying, Fire/Flying, Water/Flying, Electric/Flying, Grass/Flying, Ice/Flying, Fighting/Flying, Poison/Flying, Ground/Flying, Flying/Psychic, Flying/Bug, Flying/Rock, Flying/Ghost, Flying/Dragon, Flying/Dark, Flying/Steel, Flying/Fairy]"
53,Ground,Resistant (0.25),1,[Grass/Bug]
54,Ground,Resistant (0.5),22,"[Grass, Bug, Normal/Grass, Normal/Bug, Water/Grass, Water/Bug, Grass/Ice, Grass/Fighting, Grass/Ground, Grass/Psychic, Grass/Ghost, Grass/Dragon, Grass/Dark, Grass/Fairy, Ice/Bug, Fighting/Bug, Ground/Bug, Psychic/Bug, Bug/Ghost, Bug/Dragon, Bug/Dark, Bug/Fairy]"
55,Ground,Super Effective (2),55,"[Fire, Electric, Poison, Rock, Steel, Normal/Fire, Normal/Electric, Normal/Poison, Normal/Rock, Normal/Steel, Fire/Water, Fire/Ice, Fire/Fighting, Fire/Ground, Fire/Psychic, Fire/Ghost, Fire/Dragon, Fire/Dark, Fire/Fairy, Water/Electric, Water/Poison, Water/Rock, Water/Steel, Electric/Ice, Electric/Fighting, Electric/Ground, Electric/Psychic, Electric/Ghost, Electric/Dragon, Electric/Dark, Electric/Fairy, Ice/Poison, Ice/Rock, Ice/Steel, Fighting/Poison, Fighting/Rock, Fighting/Steel, Poison/Ground, Poison/Psychic, Poison/Ghost, Poison/Dragon, Poison/Dark, Poison/Fairy, Ground/Rock, Ground/Steel, Psychic/Rock, Psychic/Steel, Rock/Ghost, Rock/Dragon, Rock/Dark, Rock/Fairy, Ghost/Steel, Dragon/Steel, Dark/Steel, Steel/Fairy]"
56,Ground,Super Effective (4),10,"[Fire/Electric, Fire/Poison, Fire/Rock, Fire/Steel, Electric/Poison, Electric/Rock, Electric/Steel, Poison/Rock, Poison/Steel, Rock/Steel]"

#### Defense

In [545]:
def groupby_categories_defensive (df):
    
    df_groupby = df.groupby(['Defensive Type', 'Weakness Category']).agg(
        Count=('Weakness Category', 'size'),
        Attacking=('Attack Type', lambda x: list(x))
    ).reset_index()
    
    return df_groupby

In [546]:
table_categories_defensive = groupby_categories_defensive (df_table_types_categories)

In [547]:
table_categories_defensive

,Defensive Type,Weakness Category,Count,Attacking
0,Bug,Neutral,12,"[Normal, Water, Electric, Ice, Poison, Psychic, Bug, Ghost, Dragon, Dark, Steel, Fairy]"
1,Bug,Resistant (0.5),3,"[Grass, Fighting, Ground]"
2,Bug,Super Effective (2),3,"[Fire, Flying, Rock]"
3,Bug/Dark,Neutral,8,"[Normal, Water, Electric, Ice, Fighting, Poison, Dragon, Steel]"
4,Bug/Dark,No Effect,1,[Psychic]
...,...,...,...,...
728,Water/Steel,Neutral,4,"[Fire, Grass, Ghost, Dark]"
729,Water/Steel,No Effect,1,[Poison]
730,Water/Steel,Resistant (0.25),2,"[Ice, Steel]"
731,Water/Steel,Resistant (0.5),8,"[Normal, Water, Flying, Psychic, Bug, Rock, Dragon, Fairy]"
732,Water/Steel,Super Effective (2),3,"[Electric, Fighting, Ground]"

In [552]:
def defensive_types_category (df, weakness_category, top=10, ascending=False):
    
    df_sorted = df[df['Weakness Category']==weakness_category].sort_values(by='Count', ascending=ascending).head(top)
    
    return df_sorted

In [555]:
defensive_types_category (table_categories_defensive, 'No Effect', top=10, ascending=False)

    Defensive Type Weakness Category  Count                     Attacking
313    Ghost/Steel         No Effect      3    [Normal, Fighting, Poison]
407   Ground/Ghost         No Effect      3  [Normal, Electric, Fighting]
278   Flying/Ghost         No Effect      3    [Normal, Fighting, Ground]
301     Ghost/Dark         No Effect      3   [Normal, Fighting, Psychic]
515   Normal/Ghost         No Effect      3     [Normal, Fighting, Ghost]
309    Ghost/Fairy         No Effect      3    [Normal, Fighting, Dragon]
263    Flying/Dark         No Effect      2             [Ground, Psychic]
545   Normal/Steel         No Effect      2               [Poison, Ghost]
273   Flying/Fairy         No Effect      2              [Ground, Dragon]
292   Flying/Steel         No Effect      2              [Poison, Ground]

In [556]:
defensive_types_category (table_categories_defensive, 'Resistant (0.25)', top=10, ascending=False)

    Defensive Type Weakness Category  Count                        Attacking
244     Fire/Steel  Resistant (0.25)      5  [Grass, Ice, Bug, Steel, Fairy]
230    Fire/Poison  Resistant (0.25)      3              [Grass, Bug, Fairy]
599   Poison/Steel  Resistant (0.25)      3              [Grass, Bug, Fairy]
249     Fire/Water  Resistant (0.25)      3               [Fire, Ice, Steel]
575  Poison/Flying  Resistant (0.25)      3           [Grass, Fighting, Bug]
331   Grass/Dragon  Resistant (0.25)      3         [Water, Electric, Grass]
293   Flying/Steel  Resistant (0.25)      2                     [Grass, Bug]
321      Grass/Bug  Resistant (0.25)      2                  [Grass, Ground]
258     Flying/Bug  Resistant (0.25)      2                [Grass, Fighting]
274   Flying/Fairy  Resistant (0.25)      2                  [Fighting, Bug]

In [557]:
defensive_types_category (table_categories_defensive, 'Resistant (0.5)', top=10, ascending=False)

,Defensive Type,Weakness Category,Count,Attacking
664,Steel,Resistant (0.5),10,"[Normal, Grass, Ice, Flying, Psychic, Bug, Rock, Dragon, Steel, Fairy]"
546,Normal/Steel,Resistant (0.5),10,"[Normal, Grass, Ice, Flying, Psychic, Bug, Rock, Dragon, Steel, Fairy]"
114,Electric/Steel,Resistant (0.5),9,"[Normal, Electric, Grass, Ice, Psychic, Bug, Rock, Dragon, Fairy]"
39,Dark/Steel,Resistant (0.5),9,"[Normal, Grass, Ice, Flying, Rock, Ghost, Dragon, Dark, Steel]"
731,Water/Steel,Resistant (0.5),8,"[Normal, Water, Flying, Psychic, Bug, Rock, Dragon, Fairy]"
57,Dragon/Steel,Resistant (0.5),8,"[Normal, Water, Electric, Flying, Psychic, Bug, Rock, Steel]"
669,Steel/Fairy,Resistant (0.5),8,"[Normal, Grass, Ice, Flying, Psychic, Rock, Dark, Fairy]"
632,Psychic/Steel,Resistant (0.5),8,"[Normal, Grass, Ice, Flying, Rock, Dragon, Steel, Fairy]"
315,Ghost/Steel,Resistant (0.5),8,"[Grass, Ice, Flying, Psychic, Rock, Dragon, Steel, Fairy]"
377,Grass/Steel,Resistant (0.5),8,"[Normal, Water, Electric, Psychic, Rock, Dragon, Steel, Fairy]"

In [558]:
defensive_types_category (table_categories_defensive, 'Neutral', top=10, ascending=False)

,Defensive Type,Weakness Category,Count,Attacking
478,Normal,Neutral,16,"[Normal, Fire, Water, Electric, Grass, Ice, Poison, Ground, Flying, Psychic, Bug, Rock, Dragon, Dark, Steel, Fairy]"
610,Psychic/Dark,Neutral,15,"[Normal, Fire, Water, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Rock, Ghost, Dragon, Dark, Steel]"
59,Electric,Neutral,14,"[Normal, Fire, Water, Grass, Ice, Fighting, Poison, Psychic, Bug, Rock, Ghost, Dragon, Dark, Fairy]"
535,Normal/Psychic,Neutral,14,"[Normal, Fire, Water, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Rock, Dragon, Steel, Fairy]"
163,Fighting/Psychic,Neutral,13,"[Normal, Fire, Water, Electric, Grass, Ice, Poison, Ground, Psychic, Bug, Dragon, Dark, Steel]"
300,Ghost/Dark,Neutral,13,"[Fire, Water, Electric, Grass, Ice, Ground, Flying, Bug, Rock, Ghost, Dragon, Dark, Steel]"
20,Bug/Rock,Neutral,13,"[Fire, Electric, Grass, Ice, Fighting, Ground, Flying, Psychic, Bug, Ghost, Dragon, Dark, Fairy]"
681,Water/Dragon,Neutral,13,"[Normal, Electric, Grass, Ice, Fighting, Poison, Ground, Flying, Psychic, Bug, Rock, Ghost, Dark]"
426,Ice,Neutral,13,"[Normal, Water, Electric, Grass, Poison, Ground, Flying, Psychic, Bug, Ghost, Dragon, Dark, Fairy]"
603,Psychic,Neutral,13,"[Normal, Fire, Water, Electric, Grass, Ice, Poison, Ground, Flying, Rock, Dragon, Steel, Fairy]"

In [559]:
defensive_types_category (table_categories_defensive, 'Super Effective (2)', top=10, ascending=False)

,Defensive Type,Weakness Category,Count,Attacking
168,Fighting/Rock,Super Effective (2),7,"[Water, Grass, Fighting, Ground, Psychic, Steel, Fairy]"
628,Psychic/Rock,Super Effective (2),7,"[Water, Grass, Ground, Bug, Ghost, Dark, Steel]"
640,Rock/Dark,Super Effective (2),6,"[Water, Grass, Ground, Bug, Steel, Fairy]"
645,Rock/Dragon,Super Effective (2),6,"[Ice, Fighting, Ground, Dragon, Steel, Fairy]"
361,Grass/Ice,Super Effective (2),6,"[Fighting, Poison, Flying, Bug, Rock, Steel]"
369,Grass/Psychic,Super Effective (2),6,"[Fire, Ice, Poison, Flying, Ghost, Dark]"
467,Ice/Psychic,Super Effective (2),6,"[Fire, Bug, Rock, Ghost, Dark, Steel]"
655,Rock/Ghost,Super Effective (2),6,"[Water, Grass, Ground, Ghost, Dark, Steel]"
157,Fighting/Ground,Super Effective (2),6,"[Water, Grass, Ice, Flying, Psychic, Fairy]"
616,Psychic/Dragon,Super Effective (2),6,"[Ice, Bug, Ghost, Dragon, Dark, Fairy]"

In [572]:
defensive_types_category (table_categories_defensive, 'Super Effective (4)', top=53, ascending=False)

      Defensive Type    Weakness Category  Count           Attacking
477        Ice/Steel  Super Effective (4)      2    [Fire, Fighting]
661       Rock/Steel  Super Effective (4)      2  [Fighting, Ground]
420      Ground/Rock  Super Effective (4)      2      [Water, Grass]
432          Ice/Bug  Super Effective (4)      2        [Fire, Rock]
625    Psychic/Ghost  Super Effective (4)      2       [Ghost, Dark]
324        Grass/Bug  Super Effective (4)      2      [Fire, Flying]
471         Ice/Rock  Super Effective (4)      2   [Fighting, Steel]
241        Fire/Rock  Super Effective (4)      2     [Water, Ground]
27         Bug/Steel  Super Effective (4)      1              [Fire]
396    Ground/Dragon  Super Effective (4)      1               [Ice]
405    Ground/Flying  Super Effective (4)      1               [Ice]
437         Ice/Dark  Super Effective (4)      1          [Fighting]
445        Ice/Fairy  Super Effective (4)      1             [Steel]
453       Ice/Flying  Super Effective (4)      1              [Rock]
530       Normal/Ice  Super Effective (4)      1          [Fighting]
489      Normal/Dark  Super Effective (4)      1          [Fighting]
370    Grass/Psychic  Super Effective (4)      1               [Bug]
543      Normal/Rock  Super Effective (4)      1          [Fighting]
548     Normal/Steel  Super Effective (4)      1          [Fighting]
596      Poison/Rock  Super Effective (4)      1            [Ground]
602     Poison/Steel  Super Effective (4)      1            [Ground]
613     Psychic/Dark  Super Effective (4)      1               [Bug]
641        Rock/Dark  Super Effective (4)      1          [Fighting]
650       Rock/Fairy  Super Effective (4)      1             [Steel]
700     Water/Flying  Super Effective (4)      1          [Electric]
712     Water/Ground  Super Effective (4)      1             [Grass]
379      Grass/Steel  Super Effective (4)      1              [Fire]
358     Grass/Ground  Super Effective (4)      1               [Ice]
362        Grass/Ice  Super Effective (4)      1              [Fire]
209      Fire/Flying  Super Effective (4)      1              [Rock]
49       Dragon/Dark  Super Effective (4)      1             [Fairy]
102  Electric/Poison  Super Effective (4)      1            [Ground]
110    Electric/Rock  Super Effective (4)      1            [Ground]
116   Electric/Steel  Super Effective (4)      1            [Ground]
127     Fighting/Bug  Super Effective (4)      1            [Flying]
133    Fighting/Dark  Super Effective (4)      1             [Fairy]
137  Fighting/Dragon  Super Effective (4)      1             [Fairy]
162  Fighting/Poison  Super Effective (4)      1           [Psychic]
181         Fire/Bug  Super Effective (4)      1              [Rock]
194    Fire/Electric  Super Effective (4)      1            [Ground]
223      Fire/Ground  Super Effective (4)      1             [Water]
41        Dark/Steel  Super Effective (4)      1          [Fighting]
228         Fire/Ice  Super Effective (4)      1              [Rock]
233      Fire/Poison  Super Effective (4)      1            [Ground]
247       Fire/Steel  Super Effective (4)      1            [Ground]
261       Flying/Bug  Super Effective (4)      1              [Rock]
271    Flying/Dragon  Super Effective (4)      1               [Ice]
329       Grass/Dark  Super Effective (4)      1               [Bug]
334     Grass/Dragon  Super Effective (4)      1               [Ice]
339      Grass/Fairy  Super Effective (4)      1            [Poison]
343   Grass/Fighting  Super Effective (4)      1            [Flying]
349     Grass/Flying  Super Effective (4)      1               [Ice]
727       Water/Rock  Super Effective (4)      1             [Grass]

In [573]:
def bar_plot_weakness_category_defensive (df, defensive_type):
    
    order_list = ['Neutral', 'No Effect', 'Resistant (0.25)', 'Resistant (0.5)', 'Super Effective (2)', 'Super Effective (4)']

    custom_palette = ['#1f77b4', '#d3d3d3', '#2ca02c', '#006400', '#ff6347', '#b22222']

    fig = px.bar(
        df[df['Defensive Type']==defensive_type],
        x='Weakness Category',
        y='Count',
        color='Weakness Category',
        title=f"Defensive Effects for {defensive_type} Type",
        category_orders={'Weakness Category': order_list},
        color_discrete_map={'Neutral': custom_palette[0], 'No Effect': custom_palette[1],
                           'Resistant (0.25)': custom_palette[2], 'Resistant (0.5)': custom_palette[3],
                           'Super Effective (2)': custom_palette[4], 'Super Effective (4)': custom_palette[5]}
    )

    fig.update_layout(
        title={'x': 0.5, 'xanchor': 'center', 'y': 0.95},  
        font=dict(family="Arial", size=14),  
        yaxis=dict(tickformat=".0f", showgrid=True, gridcolor='gray', gridwidth=0.2, title=None), 
        xaxis=dict(title=None),
        plot_bgcolor='white',  
        height=600,  
        width=900,  
    )

    fig.show()
    
    return df[df['Defensive Type']==defensive_type]

In [579]:
bar_plot_weakness_category_defensive (table_categories_defensive, 'Fire/Steel')

,Defensive Type,Weakness Category,Count,Attacking
242,Fire/Steel,Neutral,5,"[Fire, Electric, Rock, Ghost, Dark]"
243,Fire/Steel,No Effect,1,[Poison]
244,Fire/Steel,Resistant (0.25),5,"[Grass, Ice, Bug, Steel, Fairy]"
245,Fire/Steel,Resistant (0.5),4,"[Normal, Flying, Psychic, Dragon]"
246,Fire/Steel,Super Effective (2),2,"[Water, Fighting]"
247,Fire/Steel,Super Effective (4),1,[Ground]

# Streamlit

In [ ]:
# Title of the app
st.title("Soccer Analytics")

# Text input
name = st.text_input("Enter your team name:")

# Button
if st.button("Submit"):
    st.write(f"Hello, {name}!")

# Slider
number = st.slider("Select a number:", 0, 100)
st.write(f"You selected: {number}")

# Create a select box
selected_league_option = st.selectbox("Choose an option:", league_names)

# Get the teams 'ids'

id_league_choice = leagues_dictionary[selected_league_option]

id_team_season = chamada_api(f'/teams?league={id_league_choice}&season=2021')

teams_ids = transform_dic_column(pd.DataFrame(id_team_season['response']), ['team'])['team_id'].tolist()
teams_names = transform_dic_column(pd.DataFrame(id_team_season['response']), ['team'])['team_name'].tolist()

teams_dictionary = dict(zip(teams_names, teams_ids))

# Create a select box
selected_team_option = st.selectbox("Choose an option:", teams_names)